### PR TITLE
BFD-2135: Add synthea bucket and group creation to terraform

### PR DESCRIPTION
**Pull request by lsmitchell**
**JIRA Ticket:**
[BFD-2135](https://jira.cms.gov/browse/BFD-2135)

**User Story or Bug Summary:**

As a BFD Engineer I would like to have the aws bucket relating to required synthea files to be recreatable in the event the bucket is lost so that I can quickly recover from a failure scenario.

---

### What Does This PR Do?

Adds the bucket creation for bfd-mgmt-synthea, along with the group policy, permissions, and attachments related to accessing the bucket for the synthea devs.
Also moves the synthea TF script to the MGMT environment location.
Updated the s3 util script used for synthea automation to the new bucket.

Noted terraform has been applied and verified in AWS console, and looks good.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mjburling — APPROVED** [review]
This looks pretty good! Obviously I've had a hand in it, but you've got a decent understanding of how this works and could make it your own if you'd like 👏

There's some _newer_ ground here with the assignment of users to groups via SSM-stored values. We borrowed this from the hast implementation of the global/kms module, and similarly, these values are **not** in terraform. It's unclear exactly how we'll manage these values moving forward, but this is a fine starting point. We'll be back here again, iterating on this solution Soon™ because we must get a lot better at this.

**Review by cbrunefearless — APPROVED** [review]
LGTM

**Comment by lsmitchell** [comment]
@mjburling added the old files to the new bucket, confirmed read/write access by Jason (Marc is out, but they have the same access so it should be good.) Also updated the S3 script to point to the new bucket as part of this PR.

**Review by cbrunefearless — DISMISSED** [review]
lgtm

**Review by mjburling — DISMISSED** [review]

**Review by mjburling — APPROVED** [review]

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Pull request merged**
