### PR TITLE
[BFD-1041] Jetty set to use custom /tmp directory

### PR DESCRIPTION
**Pull request by christrotteradhoc**
### Change Details

Deploy the BFD server with java.io.tmpdir set to a 'tmp' directory underneath the main bfd server directory rather than defaulting to the /tmp directory.
 

### Acceptance Validation

Tested on AWS test cluster. Build/deploy was successful and confirmed that the running process had the argument:
  '-Djava.io.tmpdir=/usr/local/bfd-server/tmp', checked that this directory was populated with files from jetty and that /tmp was not. Here is what that looked like:

  
$ ps -ef | grep jetty
bfd       4346  4285  4 19:17 ?        00:01:29 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/bin/java -Xmx4505m -javaagent:/usr/local/bfd-server/newrelic/newrelic.jar -XX:MaxMetaspaceSize=2048m -Xloggc:/usr/local/bfd-server/gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PreserveFramePointer -Djava.io.tmpdir=/usr/local/bfd-server/tmp  ....

$ ls -l /usr/local/bfd-server/tmp
total 488
-rw-r--r--. 1 bfd bfd 73656 Jul  2 19:17 agent-bridge2170701687449856375.jar
-rw-r--r--. 1 bfd bfd 73656 Jul  2 19:17 agent-bridge3889717330382124624.jar
-rw-r--r--. 1 bfd bfd 73656 Jul  2 19:17 agent-bridge6059220727702942278.jar
-rw-r--r--. 1 bfd bfd 73656 Jul  2 19:17 agent-bridge6292737952934919537.jar
-rw-r--r--. 1 bfd bfd 15683 Jul  2 19:17 agent-bridge-datastore2059622295531541384.jar
-rw-r--r--. 1 bfd bfd 15683 Jul  2 19:17 agent-bridge-datastore9075561824493597595.jar
-rw-r--r--. 1 bfd bfd   166 Jul  2 19:17 instrumentation100605155839695461.jar
-rw-r--r--. 1 bfd bfd  1399 Jul  2 19:18 instrumentation3041381800035870108.jar
-rw-r--r--. 1 bfd bfd   166 Jul  2 19:17 instrumentation3852251133470104649.jar
-rw-r--r--. 1 bfd bfd  1380 Jul  2 19:18 instrumentation5660727200651731645.jar
-rw-r--r--. 1 bfd bfd   166 Jul  2 19:18 instrumentation6657274234832971357.jar
-rw-r--r--. 1 bfd bfd  3326 Jul  2 19:18 instrumentation8536260234802979233.jar
drwx------. 3 bfd bfd    20 Jul  2 19:18 jetty-0_0_0_0-7443-bfd-server-war-1_0_0-SNAPSHOT_war-_-any-4447200530449440033
-rw-r--r--. 1 bfd bfd 45478 Jul  2 19:17 newrelic-api2817775885934880424.jar
-rw-r--r--. 1 bfd bfd 45478 Jul  2 19:17 newrelic-api936732376108618109.jar
-rw-r--r--. 1 bfd bfd  6356 Jul  2 19:17 newrelic-bootstrap6808108589362275865.jar
-rw-r--r--. 1 bfd bfd  6356 Jul  2 19:17 newrelic-bootstrap6876288301622557541.jar
-rw-r--r--. 1 bfd bfd  6915 Jul  2 19:17 newrelic-opentracing-bridge6084257758664883024.jar
-rw-r--r--. 1 bfd bfd  6915 Jul  2 19:17 newrelic-opentracing-bridge7679192412293872426.jar
-rw-r--r--. 1 bfd bfd  5110 Jul  2 19:17 newrelic-weaver-api4957616839909844345.jar
-rw-r--r--. 1 bfd bfd  5110 Jul  2 19:17 newrelic-weaver-api6997570902307454075.jar

$ ls -ltra /tmp
total 10552
drwxr-xr-x.  2 root     root          279 Sep 13  2019 newrelic
drwxrwxrwt.  2 root     root            6 Feb  6 07:08 .XIM-unix
drwxrwxrwt.  2 root     root            6 Feb  6 07:08 .X11-unix
drwxrwxrwt.  2 root     root            6 Feb  6 07:08 .ICE-unix
drwxrwxrwt.  2 root     root            6 Feb  6 07:08 .font-unix
drwxrwxrwt.  2 root     root            6 Feb  6 07:08 .Test-unix
-rw-rw-r--.  1 root     root            0 Feb 23 19:53 ICRC_ROLL.lck
-rw-rw-r--.  1 root     root            0 Feb 23 19:53 TRXHANDLER_ROLL.lck
-rw-r--r--.  1 ec2-user ec2-user      504 Jul  2 19:00 extra_vars.json
-rw-r--r--.  1 root     root          811 Jul  2 19:00 cwagent-base.json
-rw-r--r--.  1 root     root     10787181 Jul  2 19:01 newrelic-java.zip
drwx------.  3 root     root           17 Jul  2 19:16 systemd-private-64060c7848894cefb8e44e52f512662a-ntpd.service-em9dv8
dr-xr-xr-x. 19 root     root          265 Jul  2 19:17 ..
drwxr-xr-x.  2 root     root            6 Jul  2 19:17 hsperfdata_root
drwxr-xr-x.  2 bfd      bfd            30 Jul  2 19:17 hsperfdata_bfd
-rw-r--r--.  1 root     root         2496 Jul  2 19:18 cwagent-data-server.json
drwxrwxrwt. 11 root     root         4096 Jul  2 19:43 .

### Feedback Requested

Is there any additional testing to be performed?

### External References

- [BFD-1041](https://jira.cms.gov/browse/BFD-1041)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by christrotteradhoc** [comment]
I should probably mention as well that I lifted all of this code from the pipeline application so if there are significant changes we may want to make them in both places.

**Review by jzulim — APPROVED** [review]
LGTM. Tested in TEST env, right on!

**Review by rtravitz — APPROVED** [review]
Satisfied with the results that you found in TEST. Don't think there's anything else to do besides send it along ✨

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Pull request merged**
