### PR TITLE
BFD-2104: Add script for splitting future Synthea lines into weekly loads

### PR DESCRIPTION
**Pull request by lsmitchell**
**JIRA Ticket:**
[BFD-2104](https://jira.cms.gov/browse/BFD-2104)

**User Story or Bug Summary:**

As a BFD engineer I would like the automated synthea job to automatically split up my synthea run with future dated claims into weekly folders so that they can be picked up and loaded in the future.

---

### What Does This PR Do?

Adds a script that takes output from the new Synthea v2 run script which allows for generation of past AND future claim dates, and split the past/present data from the future data.

The script does the following:
1. Using threads, reads each file and stores its lines into memory
2. Splits up the lines based on date, per file;
    a. any line with a date less than or equal to todays date remains in the "current" bucket of line data for that file. 
    b. Any future lines get placed in a dictionary based on the week they fall into. The dictionary is keyed off the next Wednesday 2 weeks from the line's date. This is to simulate file processing time in prod for future loads.
3. After all files are read and split, the counts are validated to ensure the lines the file started with match the total of all the split lines added together, per file
4. After successful validation, folders are made for every week that was required for any file by looking at the dictionary keys. These folders are placed in <synthea dir>/bfd/output automatically
5. manifests are made for each of the future folders, using the same timestamp as the folder for the manifest, adding only the files that had lines for that date
6. Files are generated in each weeks' folder for each file that had lines for that week, plus header
7. The "current" data, which is now the original data minus the future data, overwrites the original files in the synthea dir/bfd/output

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    8. There isn't too much of a burden on reviewers.
    9. Any problems it causes have a small "blast radius".
    10. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by lsmitchell** [comment]
Going to improve the top-level documentation to include the info on where things are output and other things I included in the PR description shortly, so ignore that point for now.

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by mjburling — APPROVED** [review]
LGTM. Nothing too surprising for a script like this.

**Review by mackec1 — APPROVED** [review]
looks reasonable; again how we meld this into Jenkins will be the trick.

**Pull request merged**
