### PR TITLE
BFD-3433: Update Python3 versions to 3.11

### PR DESCRIPTION
**Pull request by dondevun**
**JIRA Ticket:**
[BFD-3433](https://jira.cms.gov/browse/BFD-3433)

**User Story or Bug Summary:**

---

Upgrade versions of Python below 3.11 to 3.11. 

Some of the `Dockerfile`s use amazon created Python3 base images; however, it appears that the 3.12 version of these uses amazonlinux2023, which no longer includes yum. To avoid some potentially complicated rewrites, the upgrade was restricted to 3.11.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [x] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by aschey-forpeople** [comment]
I found one more reference to python 3.9 https://github.com/CMSgov/beneficiary-fhir-data/blob/master/insights/terraform/projects/bb2/services/analytics/modules/lambda/main.tf#L44 Not sure if this would be in scope for this PR since it's in the BB2 area.

**Comment by sb-benohe** [comment]
Please @JFU-NAVA-PBC take a look at @aschey-forpeople comment above for the BB2 part

**Comment by JFU-NAVA-PBC** [comment]
> Please @JFU-NAVA-PBC take a look at @aschey-forpeople comment above for the BB2 part

good catch, may be in the BB2 python upgrade 3.11 task (impl phase), the assigned engineer should also take care of this tf..., I'll put notes in the SPIKE ticket BB2-2980...

**Comment by aschey-forpeople** [comment]
> > Please @JFU-NAVA-PBC take a look at @aschey-forpeople comment above for the BB2 part
> 
> good catch, may be in the BB2 python upgrade 3.11 task (impl phase), the assigned engineer should also take care of this tf..., I'll put notes in the SPIKE ticket [BB2-2980](https://jira.cms.gov/browse/BB2-2980)...



> > Please @JFU-NAVA-PBC take a look at @aschey-forpeople comment above for the BB2 part
> 
> good catch, may be in the BB2 python upgrade 3.11 task (impl phase), the assigned engineer should also take care of this tf..., I'll put notes in the SPIKE ticket [BB2-2980](https://jira.cms.gov/browse/BB2-2980)...



> > Please @JFU-NAVA-PBC take a look at @aschey-forpeople comment above for the BB2 part
> 
> good catch, may be in the BB2 python upgrade 3.11 task (impl phase), the assigned engineer should also take care of this tf..., I'll put notes in the SPIKE ticket [BB2-2980](https://jira.cms.gov/browse/BB2-2980)...

Thanks! While we're at it, I found one more https://github.com/CMSgov/beneficiary-fhir-data/blob/master/insights/terraform/projects/bb2/services/common/modules/lambda/main.tf#L38

**Review by mjburling — APPROVED** [review]

**Review by aschey-forpeople — APPROVED** [review]

**Pull request merged**
