### PR TITLE
[BFD-1111] Rotate NR keys

### PR DESCRIPTION
**Pull request by rtravitz**
### Change Details

This PR finishes [BFD-1111](https://jira.cms.gov/browse/BFD-1111). It updates New Relic keys.

### External References
- [BFD-1111](https://jira.cms.gov/browse/BFD-1111)

### Security Implications

- [ ] new software dependencies
- [ ] altered security controls
- [ ] new data stored or transmitted
- [ ] security checklist is completed for this change
- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by keithdadkins — DISMISSED** [review]
I decrypted and everything looks good.

**Review by ericbuckley — APPROVED** [review]

**Comment by rtravitz** [comment]
Updated with different keys for each env.

**Review by keithdadkins — APPROVED** [review]
I decrypted and verified each environment has a matching license key in new relic per each environment. Thank you for this!

**Comment by keithdadkins** [comment]
* I also verified each environment has a matching metrics key as well

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Pull request merged**
