### PR TITLE
BFD-704: Resolve intermittent SocketExceptions in tests

### PR DESCRIPTION
**Pull request by karlmdavis**
### Change Details

I've been getting a lot of intermittent test failures like the following:

```
Running gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT
Tests run: 15, Failures: 0, Errors: 2, Skipped: 4, Time elapsed: 53.651 sec <<< FAILURE! - in gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT
loadInitialEnrollmentShouldCount12(gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT)  Time elapsed: 0.128 sec  <<< ERROR!
org.flywaydb.core.internal.dbsupport.FlywaySqlException:

Unable to obtain Jdbc connection from DataSource
------------------------------------------------
SQL State  : 08006
Error Code : -1305
Message    : connection exception: connection failure: java.net.SocketException: Connection reset

        at gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT.loadInitialEnrollmentShouldCount12(RifLoaderIT.java:321)
Caused by: java.sql.SQLTransientConnectionException: connection exception: connection failure: java.net.SocketException: Connection reset
        at gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT.loadInitialEnrollmentShouldCount12(RifLoaderIT.java:321)
Caused by: org.hsqldb.HsqlException: connection exception: connection failure: java.net.SocketException: Connection reset
        at gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT.loadInitialEnrollmentShouldCount12(RifLoaderIT.java:321)

loadInitialEnrollmentShouldCount20SinceThereIsAUpdateOf8Months(gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT)  Time elapsed: 0.114 sec  <<< ERROR!
org.flywaydb.core.internal.dbsupport.FlywaySqlException:

Unable to obtain Jdbc connection from DataSource
------------------------------------------------
SQL State  : 08006
Error Code : -1305
Message    : connection exception: connection failure: java.net.SocketException: Connection reset

        at gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT.loadInitialEnrollmentShouldCount20SinceThereIsAUpdateOf8Months(RifLoaderIT.java:375)
Caused by: java.sql.SQLTransientConnectionException: connection exception: connection failure: java.net.SocketException: Connection reset
        at gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT.loadInitialEnrollmentShouldCount20SinceThereIsAUpdateOf8Months(RifLoaderIT.java:375)
Caused by: org.hsqldb.HsqlException: connection exception: connection failure: java.net.SocketException: Connection reset
        at gov.cms.bfd.pipeline.ccw.rif.load.RifLoaderIT.loadInitialEnrollmentShouldCount20SinceThereIsAUpdateOf8Months(RifLoaderIT.java:375)

Running gov.cms.bfd.pipeline.ccw.rif.CcwRifLoadJobIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.118 sec - in gov.cms.bfd.pipeline.ccw.rif.CcwRifLoadJobIT
Running gov.cms.bfd.pipeline.ccw.rif.extract.s3.task.ManifestEntryDownloadTaskIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.765 sec - in gov.cms.bfd.pipeline.ccw.rif.extract.s3.task.ManifestEntryDownloadTaskIT

Results :

Tests in error:
  RifLoaderIT.loadInitialEnrollmentShouldCount12:321 » FlywaySql
Unable to obta...
  RifLoaderIT.loadInitialEnrollmentShouldCount20SinceThereIsAUpdateOf8Months:375 » FlywaySql
```

This change resolves those test failures.

We weren't being consistent in how we checked for and reserved the port, across everything. As a result, we were often reserving ports that were available on 127.0.0.1, but not on "*", which is what HSQL was actually binding to.

This may have been particularly rough on CMS laptops, as one of the applications installed for CMS Mac OS users likes to bind a whole bunch of high-number random ports. Things seemed to get worse recently, where I could almost never get a build to succeed due to these `SocketException`s.

### Acceptance Validation

1. Is the code correct?

### Feedback Requested

1. What's your favorite kind of pasta?

### External References

- [BFD-704](https://jira.cms.gov/browse/BFD-704)

### Security Implications

This change set has no identified security implications.

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by mackec1 — APPROVED** [review]

**Comment by mackec1** [comment]
Thanks; hit the test failures a couple of times yesterday and this seems to make things right.

**Review by rtravitz — APPROVED** [review]
Tests pass. I didn't experience the intermittent failure, but if it seems like this will help, then all for it.

Favorite pasta is either bucatini or orecchiette, though the advent of cascatelli could certainly change the equation.

**Review by mackec1 — APPROVED** [review]

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Comment by karlmdavis** [comment]
> @rtravitz Also the only thing to be aware of is whether you were counting on the upgrades to HSQL and Flyway that were rolled back in #546 being in place. There's a ticket to upgrade those that will end up in the next sprint.

Nope, this all should be independent of that. And since it compiles and the tests still pass, it definitely is.

**Review by rtravitz — APPROVED** [review]
✨

**Comment by karlmdavis** [comment]
Weird, and then it suddenly decided it had enough reviews. I'd guess there was a bug and GitHub fixed it.

**Pull request merged**
