### PR TITLE
Adds slack notifications to Jenkinsfile

### PR DESCRIPTION
**Pull request by keithdadkins**
### Change Details
Adds Slack notifications to builds (via Jenkinsfile).

_** Note: working with scripted style pipelines is very different from declarative pipelines. They use different syntax which required the use of try catch blocks instead of post blocks for triggering notifications. Just a heads up if you are only used to declarative._

### Acceptance Validation
Review slack notifications in the #bfd-build-status channel (after a few test deployments) to ensure messages include the following:
  - Build number
  - Branch 
  - Stage of failure 
  - Build URL
  - Job name 
  - Who launched the build

Test deployments should cover successful builds, successful but unstable builds, aborted builds, and failed builds.

Any glaring issues. Cases that I may have missed.

Please see #bfd-build-status slack for example builds.

### Feedback Requested
Please feel free to offer suggestions on message content/layout. I'm open.

### External References
- [BFD-529](https://jira.cms.gov/browse/BFD-529)

### Security Implications
- This addition does not require any unsafe script approvals in Jenkins.

### CODE REVIEW

**Review by cbrunefearless — DISMISSED** [review]
lgtm

**Review by jzulim — APPROVED** [review]
The tests look great. Messaging, fields, link to job and colors all look great.

**Review by mackec1 — APPROVED** [review]
Keith; only nit was when I tried to find the #bfd-build-status channel; found it at #bfd-builds.

**Comment by keithdadkins** [comment]
> Keith; only nit was when I tried to find the #bfd-build-status channel; found it at #bfd-builds.

I had them rename the channel. It's now %37.5 shorter :)

**Pull request merged**
