### PR TITLE
BCDA 4497: Update Insights Lambda Runtime to 14.x

### PR DESCRIPTION
**Pull request by lostpurplecow**
### Change Details

NodeJS 10.x is nearing its [runtime support policy](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html).

This updates the `bcda_load_partitions` Lambda to use latest runtime available.

### Acceptance Validation

- Lambda behaves the same

### External References

- https://jira.cms.gov/browse/BCDA-4497

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by msnook — DISMISSED** [review]
This looks good to me.  Were you able to generate a `terraform plan`?  Was the change already applied?

**Review by cbrunefearless — DISMISSED** [review]
lgtm

**Review by msnook — APPROVED** [review]
Looks good!
```
  # aws_lambda_function.bcda_load_partitions will be updated in-place
  ~ resource "aws_lambda_function" "bcda_load_partitions" {
        arn                            = "arn:aws:lambda:us-east-1:<REDACTED>:function:bcda_load_partitions"
        description                    = "Loads partitions for tables"
        filename                       = "./lambda.zip"
        function_name                  = "bcda_load_partitions"
        handler                        = "index.handler"
        id                             = "bcda_load_partitions"
        invoke_arn                     = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:<REDACTED>:function:bcda_load_partitions/invocations"
        last_modified                  = "2021-05-17T19:30:33.136+0000"
        layers                         = []
        memory_size                    = 128
        publish                        = false
        qualified_arn                  = "arn:aws:lambda:us-east-1:<REDACTED>:function:bcda_load_partitions:$LATEST"
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::<REDACTED>:role/BcdaLoadPartitions-20210212142716462600000002"
      ~ runtime                        = "nodejs10.x" -> "nodejs12.x"
        source_code_hash               = "dNm85SEa9SdSKvj77nV9e1WYsSbrwB7YgNHUCIoWEsQ="
        source_code_size               = 674
        tags                           = {}
        timeout                        = 90
        version                        = "$LATEST"

        tracing_config {
            mode = "PassThrough"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

```

**Review by msnook — APPROVED** [review]

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Pull request merged**
