### PR TITLE
BFD-609: Enabled BFD V2 for local development

### PR DESCRIPTION
**Pull request by jzulim**
### Change Details

This code change configures the server-start.sh to accept and pass a boolean value to determine if the BFD V2 endpoints should be enabled. It set's this flag as 'true' by default. This script is only used for local dev. 

### Acceptance Validation

Once built and the bfd-server started, you can access /v2/fhir/Patient , etc. 

### Feedback Requested

Are the documentation updates sufficient?
Does this only impact local development? Hopefully, yes. :)

### External References

- [BFD-609](https://jira.cms.gov/browse/BFD-609)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by JFU-GIT** [comment]
tried started a local bfd server with v1 and v2 enabled (by default) successfully on a linux (Ubuntu 18), works as expected, left some comments about readme.
also tried the PR starting docker container from contributing directory: i.e. make servable, make loadable, make up, make load.
works great.

**Review by keithdadkins — APPROVED** [review]
LGTM

**Review by JFU-GIT — APPROVED** [review]
looks good to me.

**Review by mackec1 — APPROVED** [review]
As noted by others, README(s) are a bit out-of-date and/or lacking in clarity. But as far as the actual implementation of the feature flag, etc. things are good to go.

**Pull request merged**
