### PR TITLE
BFD-2102: Implement Jenkins availability pipeline to populate our BFD Server availability SLI

### PR DESCRIPTION
**Pull request by malessi**
**JIRA Ticket:**
[BFD-2102](https://jira.cms.gov/browse/BFD-2102)

**User Story or Bug Summary:**

As a BFD Engineer, I want an SLI to be captured indicating service availability for the BFD Server so that I can use it for our availability SLOs

---

### What Does This PR Do?

This PR adds two new Jenkins pipelines, one that builds a Docker image, `bfd-availability-checker`,
based on Alpine called `bfd-availability-checker-build` and another that is used to check the
availability of the BFD Server called `bfd-availability-checker`.

The `bfd-availability-checker` Docker image is a small Alpine image that includes `aws-cli` and
`curl`, both needed for use in the `bfd-availability-checker` Jenkins pipeline. As this image is
required for use in the aforementioned pipeline, and we do not yet have a means for defining an
`imagePullSecret` for our Jenkins' k8s cluster, this image is stored in our public ECR.

The main pipeline this PR adds, `bfd-availability-checker`, is a Jenkins pipeline that is intended
to be run once per-minute. This pipeline runs a simple `curl` against each environment's
`/metrics/ping` endpoint looking for a `200 OK` response. If a `200 OK` is returned from the
request, a value of `1` is submitted to the `availability/success` metric under the
`bfd-{ENV}/bfd-server` namespace. Conversely, if a non-`200` response is returned _or_ if `curl`
itself fails a value of `1` is submitted to the `availability/failure` metric in CloudWatch, and the
corresponding Jenkins pipeline build will be marked as `UNSTABLE`.

With these new metrics we will be able to calculate uptime percentages for the BFD Server and thus
start measuring our availability SLOs more accurately.

Note that this pipeline is not currently running at this time. Declarative pipelines are
_post-processed_, therefore the `cron` trigger defined in the `Jenkinsfile` is not active until the
**next** build of `bfd-availability-checker` which I will do once this PR is merged.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

- Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

- If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

  - Does this PR add any new software dependencies?
    - [ ] Yes
    - [x] No
  - Does this PR modify or invalidate any of our security controls?
    - [ ] Yes
    - [x] No
  - Does this PR store or transmit data that was not stored or transmitted before?
    - [ ] Yes
    - [x] No

- If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
  - Do you think this PR requires additional review of its security implications for other reasons?
    - [ ] Yes
    - [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

- N/A

### Submitter Checklist

I have gone through and verified that...:

- [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
- [x] This PR is reasonably limited in scope, to help ensure that:
  1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
  2. There isn't too much of a burden on reviewers.
  3. Any problems it causes have a small "blast radius".
  4. It'll be easier to rollback if that becomes necessary.
- [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
- [x] The data dictionary has been updated with any field mapping changes, if any were made.
- [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
- [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
- [x] Reviews are requested from both:
  - At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
  - Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
- [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
  - Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by lsmitchell — COMMENTED** [review]
No particular objection, but I don't get why it's creating/discarding a pod every minute instead of just keeping one alive for some set time (24h?) and running a thing every minute within it? I meant to ask yesterday when we were talking about it.

**Comment by malessi** [comment]
> No particular objection, but I don't get why it's creating/discarding a pod every minute instead of just keeping one alive for some set time (24h?) and running a thing every minute within it? I meant to ask yesterday when we were talking about it.

@lsmitchell: just to preface, I'm not much of a fan of using Jenkins like this myself. Jenkins isn't necessarily the best tool for short, frequently-ran jobs like this, but it's the most _convenient_ tool for us at the moment. On the other hand, I don't think creating three very lightweight containers every minute is a _huge_ concern. If I'd have to guess, the overhead of Jenkins orchestrating the pipeline is much, much more significant than starting and tearing down the `alpine`-based containers.

It would be possible to rewrite this pipeline such that it is no longer short-lived. For example, the `cron` trigger could be changed to every hour or every day, and the `Run availability check` stage could run continuously during that period executing availability checks on a shorter interval (i.e. 1 minute, 30 seconds). At the time of creating this pipeline, I didn't do this because it felt more "wrong", as pipelines and jobs should do one thing (build, run some steps, etc.) and exit; adding a mini "scheduler" into a pipeline complicates this and makes the process more brittle. Additionally, since Jenkins handles the scheduling and the process is so short if the pipeline fails for any reason that failure does not affect subsequent availability checks.

However, I have spent a bit of time refactoring the pipeline according to the above paragraph and I believe it is also a valid way to implement this process. Comparing the two:

| Method | Pros | Cons |
| --- | --- | --- |
| As-is | - Short-lived, single-purpose pipeline<br>- Easy to reason about<br>- Self-scheduling using Jenkins' `cron` trigger<br>- Failures with the pipeline _itself_ are also short-lived and only affect the single run; the next run of the pipeline will be unaffected by a previous failure | - A lot of unnecessary orchestration overhead for a process that is basically a two-line shell script (`curl` then `aws cloudwatch put-metric-data`) -- whether this overhead is _meaningful_ is something we have to decide  |
| Long-running `Run availability check` stage | - Significantly reduced overhead (assuming it's a concern), even when running the pipeline overall on an hour interval -- this is the **biggest** benefit with this solution<br>- Similar to (1) but less calls to SSM<br>- Availability checks could execute on an interval shorter than 1 minute<br> | - _Slightly_ more complicated code<br>- Breaks the "do one thing then exit" semantics that pipelines should follow<br>- Requires our own "scheduler" (in quotes because it's a fairly simple loop) within a scheduled (via the `cron` trigger) pipeline<br>- More prone to failure -- if a run fails midway we would require additional failure handling to restart the pipeline and not lose any data |

I am going to give this some thought as I am not entirely sure which one is preferable right now.

**Comment by malessi** [comment]
After doing some more thinking I believe keeping the pipeline as-is for the time-being will work fine for us. After adjusting each parallel run (each `matrix` `axis`, i.e. environment) to run on the same pod instead of separate pods the pipeline now runs consistently in about 30 seconds including scheduling, SCM checkout, and pipeline steps. By a _significant_ margin the longest step is downloading the TLS certificate from SSM, so I would have to assume that the overhead of starting the pod and running the pipeline is minimal.

If for some reason we find that the current solution does not work for us I have kept the refactored "long-running" version.

**Review by mjburling — APPROVED** [review]

**Review by lsmitchell — APPROVED** [review]
Thanks for the extra thought; I'll defer to your much more detailed and well-thought out opinion here.

**Pull request merged**
