### PR TITLE
[BFD-692] Install and configure amazon-efs-utils on ETL

### PR DESCRIPTION
**Pull request by keithdadkins**
### Change Details
The default amazon-efs-utils on rhel 7 is not capable of creating secure tunnels to amazon's efs service for several reasons:
1. The version of stunnel in rhel 7 (version 4 something) is wildly  outdated
2. The default amazon-efs-utils is not running in fips mode
3. The default stunnel is not configured for fips mode

This commit adds an ansible role that replaces the outdated stunnel with a manually compiled (with fips) version, installs a fips compatible version of amazon-efs-utils, and configures the server accordingly.

This role is imported into our ETL pipeline build so that our ETL instances can securely mount EFS file systems using IAM.

### Acceptance Validation
- No glaring issues
- A successful deployment to test has been performed and efs mount verified

### External References

- [BFD-692](https://jira.cms.gov/browse/BFD-692)
- [BFD-477](https://jira.cms.gov/browse/BFD-477)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by keithdadkins** [comment]
A few TODO's on this:
1. If/when we move to Amazon Linux I'll need to filter out rhel 7 plays because I believe they both are in the "RedHat" ansible_os_family
2. This adds about 8 minutes to builds (manually compiling stunnel). I can reduce this by caching stunnel and amazon-efs-utils bins (unless versions change) if this becomes a problem.

**Comment by keithdadkins** [comment]
I deployed to test and was able to mount an EFS file system using IAM authentication (e.g., using instance profile role).

**Review by jzulim — APPROVED** [review]
lgtm

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Comment by keithdadkins** [comment]
I created https://jira.cms.gov/browse/BFD-694 to speed up builds by caching artifacts.

**Pull request merged**
