### PR TITLE
BFD-2020 configure: open telemetry for migrator, pipeline, & server 

### PR DESCRIPTION
**Pull request by kcirtapfromspace**
**JIRA Ticket:**
[BFD-2020](https://jira.cms.gov/browse/BFD-2020)

**User Story or Bug Summary:**

As a BFD Engineer, I want a single dashboard that reliably reports the overall system's availability, defined as the system's ability to perform primary and ancillary functions as expected. To enable that holistic view please enable cloudwatch agent functionality to consume OpenTelemetry metrics 
---

### What Does This PR Do?

This PR configures open telemetry for migrator, pipeline, & server. 
* AWS cloudwatch agent is configured to start the open-telemetry process on instance 
* [AWS Distro for OpenTelemetry Java Auto-Instrumentation and X-Ray](https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr ) JAR is downloaded to server/ami into app directory. 
* Application startup script is configured to run with  OpenTelemetry Java Auto-Instrumentation
### OpenTelemetry Java Agent Features

This lists out some of the features specific to java agents that OpenTelemetry Auto Instrumentation
provides.

- Bundled exporters
  - [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md)
  - Jaeger gRPC
  - Logging
  - Zipkin
- Bundled propagators
  - [W3C TraceContext / Baggage](https://www.w3.org/TR/trace-context/)
  - All Java [trace propagator extensions](https://github.com/open-telemetry/opentelemetry-java/tree/main/extensions/trace-propagators)
- Environment variable configuration as per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md)
  - Additional support for system properties for same variables by transforming UPPER_UNDERSCORE -> lower.dot
  - Ability to disable individual instrumentation, or only enable certain ones.
- Ability to load a custom exporter via an external JAR library
- Isolation from application
  - Separate Agent class loader with almost all agent-specific classes
    - OpenTelemetry SDK initialized in Agent class loader
  - Shading of instrumentation libraries when used in agent
  - API bridge for application usage of API to access the Agent class loader's SDK
    - API bridge not applied if user brings incompatible API version, preventing linkage errors (similar to safety mechanism below)
- [Safety mechanisms](./safety-mechanisms.md) to prevent application linkage errors
  - Collect all references from instrumentation to library and only apply instrumentation if they exist in application
  - Verify above at compile time
  - Instrumentation tests that run the java agent in a near-production configuration
  - Ability to run tests against a fixed version and the latest version of dependencies
  - Docker-based smoke tests to verify agent behavior across JVM runtimes, Java application servers
- Ability to create custom distributions, agents with different components / configuration
  - Can set different defaults for properties
  - Can customize tracer configuration programmatically
  - Can provide custom exporter, propagator, sampler
  - Can hook into bytebuddy to customize bytecode manipulation
- Noteworthy instrumentation
  - Log injection of IDs (logback, log4j2, log4j)
  - Automatic context propagation across `Executor`s
  - Ability to instrument methods in the application if user adds `@WithSpan` annotation

### OpenTelemetry Supported libraries, frameworks, application servers, and JVMs
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md

#### Cloud watch metrics exporter config
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

Cost: Note, that collecting & reporting on any metrics will incur AWS cost related to [Cloudwatch Pricing](https://aws.amazon.com/cloudwatch/pricing/) This PR was ran in test for about a week & assumptions that the full collection of opentelemetry metrics incurred a ~$20 to ~$35 daily costs. 
image

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [x] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

Server role permissions will need to applied before metrics will appear in cloudwatch https://github.com/CMSgov/beneficiary-fhir-data/pull/1280

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:
X-Ray Permissions https://github.com/CMSgov/beneficiary-fhir-data/pull/1280
[x] Perform validations in test environment

### Submitter Checklist

I have gone through and verified that...:
Metrics & Logs are namespace, Services report metrics & dashboards can be templated from outputs. 
* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by keithdadkins** [comment]
I did not have a lot of time to look this over thoroughly, but I'm seeing new libraries, new listening ports, and new AWS services. 

If we have not done so already, we will need to run these changes by our ISSO before deploying and make sure we will not require a SIA to be completed first.

We will also need to double check with Greg to ensure our SSP/SDD's are updated to reflect these changes when/if approved/deployed.

**Review by StewGoin — COMMENTED** [review]
I have some questions around:
- What data are we expect to be grabbing from the various components / environments?
- What does that data flow / lifecycle look like?
- Where does the dashboard this all is intended to feed live?

It's probably worth getting a quick meeting / huddle together to just walk it through -- I am definitely a fan of us improving and making better use of our instrumentation, I just need some education from the team on the particulars as open telemetry isn't something I've had much contact with yet.

**Review by mackec1 — DISMISSED** [review]
Far from deep knowledge/understanding of the OpenTelemetry, but it certainly appears to setup the open telem listener; much of the yaml and terraform artifacts appear to come from burling's work, which I've reviewed with him. Looks good.

**Review by StewGoin — APPROVED** [review]
After team discussion last week, ISSO is ok with this moving ahead.

**Pull request closed without merging**
