### PR TITLE
BFD-1028: Fix table order during TRUNCATE in ITs

### PR DESCRIPTION
**Pull request by karlmdavis**
### Change Details

Things were blowing up when building against PostgreSQL. This should fix that.

### Acceptance Validation

1. Does the GH Actions build still pass (which uses HSQL DB)?
2. Can someone build it locally against PostgreSQL?

### Feedback Requested

(see previous)

### External References

- [BFD-1028](https://jira.cms.gov/browse/BFD-1028)

### Security Implications

This PR has no security implications.

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by mackec1 — APPROVED** [review]
LGTM

**Comment by christrotteradhoc** [comment]
The fix needs some rework which was discussed offline to use either a cascade option or truncate all of the tables at once on postgres only (those options are not supported in hsql).

**Review by christrotteradhoc — CHANGES_REQUESTED** [review]
The fix needs some rework which was discussed offline to use either a cascade option or truncate all of the tables at once on postgres only (those options are not supported in hsql).

**Comment by christrotteradhoc** [comment]
This was fixed under another PR

**Pull request closed without merging**
