### PR TITLE
[BFD-907] Enable BFD API V2 in PROD

### PR DESCRIPTION
**Pull request by jzulim**
### Change Details

This change sets the `data_server_v2_enabled `to `true` for the BFD PROD API servers thus enabling all BFD V2 FHIR Resources and Endpoints (i.e. /v2/fhir/Patient, etc.) 

This change also adds V2 endpoints (and an additional EOB check) to the bfd-server.sh startup script. Is this a good idea?

### Acceptance Validation

Did I set the correct environment variable?

### Feedback Requested

Are we ready for this? :)
Do you all agree having a EOB API check during bfs-server startup is helpful? It would have prevented last weeks PG12 migration incident, because patient and coverage resources performed well, EOB was hosed. 

### External References

- [BFD-907](https://jira.cms.gov/browse/BFD-907)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by mackec1 — DISMISSED** [review]
rock 'n roll

**Review by JeremyIR — APPROVED** [review]
LGTM!

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by keithdadkins — APPROVED** [review]
The startup script could use some love at some point, but otherwise looks ok to me.

**Review by mackec1 — APPROVED** [review]

**Pull request merged**
