### PR TITLE
BFD-3269: Create Architectural Diagrams as Code

### PR DESCRIPTION
**Pull request by brandoncruz3**
**JIRA Ticket:**
[BFD-3269](https://jira.cms.gov/browse/BFD-3269)

**User Story or Bug Summary:**

As a BFD contributor, I want to ensure that our diagrams are encoded and up-to-date for knowledge transfer.

 AC
Create new diagrams for JOA Presentations and save them in the BFD GH repo
* CCW Workflow
* 10,000 ft view of BFD AWS Infrastructure
* BFD Server Services - Production VPC

---

### What Does This PR Do?

This PR creates and adds architectural diagrams to our code base. The tool [Diagrams](https://diagrams.mingrammer.com/) is used here and allows BFD the ability to track our diagram changes in version control. 

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [X] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] The data dictionary has been updated with any field mapping changes, if any were made.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mjburling — COMMENTED** [review]
* I have mixed feelings, trending negatively, on the inclusion of lossier PNG binaries alongside and/or in place of SVGs. While I realize there are _some_ usability challenges with using SVGs directly (e.g. in presentation materials), I'm not convinced that those challenges should be overcome by storing binary formats along with the source 🤔 
* resource ingestion sequence for enrollee/beneficiary and adjudicated claims data looks to be somewhat outdated since the introduction of lambda-based signaling to the pipeline.
* unsure of the organizational split in hierarchies between docs/assets and docs/diagrams... they seem to be serving the same purpose, but differ on the tool used? We've already determined that tool-specific hierarchies are at least _somewhat_ harmful under `ops`, but... should that apply here, too?

**Comment by brandoncruz3** [comment]
> * I have mixed feelings, trending negatively, on the inclusion of lossier PNG binaries alongside and/or in place of SVGs. While I realize there are _some_ usability challenges with using SVGs directly (e.g. in presentation materials), I'm not convinced that those challenges should be overcome by storing binary formats along with the source 🤔
> * resource ingestion sequence for enrollee/beneficiary and adjudicated claims data looks to be somewhat outdated since the introduction of lambda-based signaling to the pipeline.
> * unsure of the organizational split in hierarchies between docs/assets and docs/diagrams... they seem to be serving the same purpose, but differ on the tool used? We've already determined that tool-specific hierarchies are at least _somewhat_ harmful under `ops`, but... should that apply here, too?

Yeah, agree with you on the lossier PNG format. I can update these to be SVG and reside in the assets directory. I can update these sequence plantuml diagrams as well. Will condense these to all reside in docs/assets. Thanks!

**Review by mjburling — COMMENTED** [review]
We've got SVGs now 👍 

1. Based on [this issue](https://github.com/mingrammer/diagrams/issues/26), it doesn't seem possible to embed SVGs at all in a resultant SVG out of the box, and of course, the embedded PNGs don't resolve from the locally-available paths, e.g. `/opt/homebrew/lib/python3.11/site-packages/resources/aws/storage/simple-storage-service-s3.png`. However, there _might_ be an acceptable solution in the commentary on that same issue to make this better. Alternatively, we could probably forego the specific images all together. Having the icons for e.g. an EC2 icon to represent a server workload doesn't do all that much to improve our understanding, does it?

3. There are modifications to `bfd-resource-digration.plantuml` but the resultant SVG hasn't been updated.

4. Did we want to update `bfd-pipeline-ccw-ingestion.plantuml` to depict the signaling/scheduling here?

5. Are we comfortable with file names like `BFD FHIR Service - Production VPC.svg`, spaces and all?

**Review by keithdadkins — APPROVED** [review]

**Review by mackec1 — APPROVED** [review]
Nice!

**Pull request merged**
