### PR TITLE
AB2D-2676 Production Validation Cert

### PR DESCRIPTION
**Pull request by wnyffenegger**
### Change Details

Adding the AB2D production validation environment's public cert for deployment to the BFD prod environment.

### Acceptance Validation

If the environment can run jobs against production after this cert has been added.

### External References

- [AB2D-2676](https://jira.cms.gov/browse/AB2D-2676)

### Security Implications

Gives AB2D production validation environment access to prod data. The AB2D production validation environment is not accessible outside of the VPN and has no API exposed.

- [ ] new software dependencies

- [x] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by jzulim** [comment]
Can I ask that you re-do the cert and give it a CN name something like ab2d-prod-validation-client - we key off the SSL cert to segment our monitoring / SLO's, etc. If it's kept the same CN as the actual PROD cert, we'll have a tougher time distinguishing the traffic.

**Comment by jzulim** [comment]
Validating Cert:

```
jzmbp:files johnzulim$ openssl x509 -in client_data_server_ab2d_prod_validation_certificate.pem  -text -noout
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            b4:1f:ae:6e:34:98:0a:6b
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = ab2d-prod-validation-client
        Validity
            Not Before: Nov 19 17:46:32 2020 GMT
            Not After : Nov 18 17:46:32 2025 GMT
        Subject: CN = ab2d-prod-validation-client
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
                Modulus:
                    00:cb:12:98:f7:c8:b5:a5:ff:5d:02:6f:7a:72:fe:
                    19:f8:d6:24:ef:3e:06:ec:db:b5:fa:4a:db:b2:78:
                    8d:0c:0d:73:85:db:7b:17:87:c3:69:bc:64:83:ba:
                    d9:b3:74:38:51:a2:41:30:10:a0:90:9c:0d:12:94:
                    e2:35:e5:f3:1e:14:69:c8:21:2c:a8:05:f0:b4:ef:
                    30:a7:16:62:cb:a7:67:ab:8e:09:17:13:68:9e:6c:
                    82:46:7d:7b:a0:80:ab:18:11:14:e4:e8:97:be:be:
                    63:d3:92:bd:77:c2:a2:92:56:d0:d3:9d:4a:08:1a:
                    4e:d4:b8:a5:de:05:45:7c:91:4e:c1:67:45:d7:c1:
                    32:96:8d:c8:08:10:4d:06:55:0c:e1:67:9e:70:17:
                    12:7a:b4:48:39:0f:75:e4:45:af:d6:63:ab:40:f2:
                    5b:6c:62:35:55:b8:28:0b:7b:be:47:91:96:ab:90:
                    d8:b5:16:8b:e4:31:6a:09:d0:76:7e:a1:15:e7:d5:
                    d1:95:a9:e5:80:7b:fe:fb:b7:1b:df:85:6e:f6:8a:
                    bf:ea:26:ed:f4:b3:4a:2f:63:b3:82:a7:00:36:81:
                    63:f1:d8:9f:f2:85:4e:18:90:5f:27:5a:49:5e:09:
                    fc:ef:61:83:7e:e0:50:13:0c:f7:84:ba:d3:38:95:
                    52:bc:a0:64:86:61:84:dd:3e:95:78:dd:14:b9:d2:
                    7e:4a:bf:fd:c5:3c:31:21:d7:e5:bf:51:2f:1f:57:
                    f7:0a:71:b8:a9:b3:58:d6:23:bd:78:e0:6b:d3:68:
                    d0:b1:e6:ca:de:e5:37:f2:5d:19:70:a4:1a:f0:f9:
                    a5:e4:26:3a:9d:25:a9:66:0e:56:1d:ab:42:b3:3f:
                    27:60:4f:15:91:7b:57:3a:29:86:87:cc:bf:2c:2e:
                    da:fa:c4:b1:e6:dd:d2:fc:5e:e5:1b:03:85:f2:6b:
                    3b:cc:82:ca:38:4b:54:ac:e5:37:aa:9c:77:a2:f9:
                    a1:63:53:4e:6c:94:5c:2b:8b:4e:52:0b:da:98:51:
                    ac:c7:73:af:3a:21:7f:6b:67:89:b7:fb:99:80:f4:
                    8c:eb:44:5a:ec:21:9b:7a:21:d4:e6:d1:32:26:d0:
                    cd:ce:ae:55:d4:1f:f4:72:f8:c0:56:2e:76:65:8f:
                    21:1c:9c:e7:b7:3f:d6:bc:97:f9:3f:6c:06:49:80:
                    eb:88:48:64:b7:7f:1a:b1:e0:6d:36:a9:ae:aa:5a:
                    c7:66:d9:7c:95:21:86:6c:6a:0b:50:25:05:3b:f9:
                    3c:68:81:c2:f0:1c:f3:54:b4:65:4a:73:3d:39:4d:
                    a1:8e:80:73:f6:72:10:fe:22:b9:5f:61:c9:cb:02:
                    27:57:5f
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         a4:06:39:79:10:af:54:83:66:fd:52:42:2b:43:fc:22:f0:df:
         fd:32:46:a1:25:a3:46:fb:47:77:7e:1d:d7:bb:7b:7f:b3:7d:
         71:94:42:53:60:2a:77:6f:a0:1d:d0:4e:8b:9e:8d:60:dd:5f:
         9f:57:78:e7:8e:bb:5f:06:50:9d:3e:49:f7:68:a7:36:8e:a1:
         3c:db:59:be:3e:5d:e5:0f:64:d7:dc:d0:97:c6:e3:7a:2d:e4:
         f7:d8:de:e4:45:24:92:dc:05:85:1d:de:86:30:91:e3:3a:6c:
         5d:bc:ee:77:e0:ad:32:9a:d8:d1:d1:a8:a3:04:c7:ca:4f:10:
         41:05:69:ba:be:fc:72:26:4b:b4:46:7f:3f:e9:69:f3:a4:61:
         14:5b:0e:06:58:61:4c:d2:74:83:ec:4f:b4:30:b8:50:68:f4:
         c1:fc:53:d6:43:81:4b:c2:b2:1a:a6:30:58:f5:32:f5:93:f8:
         4a:3d:f7:c8:c6:ac:61:2c:a8:54:1c:18:b1:87:42:30:0f:21:
         ca:11:30:8f:2f:24:3d:94:64:70:27:56:51:62:41:2f:eb:70:
         0d:e9:a9:e9:08:ba:31:61:fc:cd:83:37:de:a1:71:62:69:a7:
         d6:2b:63:77:4d:84:03:d2:d0:7b:1b:c7:04:3e:a0:99:64:13:
         ea:23:6b:c1:cb:00:37:99:b0:01:75:c7:54:72:80:bb:1f:6b:
         63:d2:0b:9c:5f:82:ab:aa:6f:7b:03:02:6e:43:53:8a:07:a2:
         a0:d7:49:f8:a0:fa:3a:33:ba:d2:ba:f9:5b:07:38:75:02:b0:
         f4:c5:05:2f:8d:20:ae:e5:84:80:38:6a:19:66:6f:64:7f:ce:
         df:f1:ea:bb:22:6f:b2:6b:31:f1:a2:68:36:a8:20:66:f0:69:
         11:47:e6:c1:b4:f0:b4:da:7c:2b:07:ad:61:95:2b:3e:5c:ce:
         36:eb:fe:aa:32:83:98:a4:01:63:84:56:51:fc:4e:d3:57:94:
         ab:5f:ee:32:68:2e:ec:a5:c6:be:b1:4f:fc:45:af:6c:09:28:
         01:88:60:76:e5:39:9b:2f:4d:93:ae:dc:3b:7e:fc:a8:51:ad:
         96:fb:ac:ba:e6:bf:ba:8f:b7:0a:07:c2:20:8f:e1:fb:1d:ba:
         08:e6:76:5a:72:59:d3:bf:66:84:57:c5:2e:1b:57:ba:71:e6:
         f8:dc:a7:69:33:12:4c:fc:35:68:d3:76:eb:92:c3:c4:a8:a0:
         5e:e3:6b:d3:6b:fe:5f:54:24:84:cb:a3:38:08:c7:5c:36:02:
         33:10:5a:58:6c:8d:4e:0c:60:09:f1:f4:2f:d1:3c:ce:48:79:
         54:6c:4c:c6:d1:ef:bf:8f
```

**Review by jzulim — APPROVED** [review]
Approved. Looks good.

**Review by njdister — APPROVED** [review]
I validated the certs and got the same result as @jzulim, LGTM

**Pull request merged**
