### PR TITLE
[BFD-624] Decommission MCT from BFD

### PR DESCRIPTION
**Pull request by keithdadkins**
### Change Details
Removes MCT related infrastructure, data-sets, and code from BFD as they no longer interact with our API.

This is a WIP as I discover what all needs to be removed.

### External References

- [BFD-624](https://jira.cms.gov/browse/BFD-624)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by karlmdavis — DISMISSED** [review]
Great work finding all that!

But could you please only keep the Ansible + Terrraform commit? All the commits that yank sample resources should be dropped/reverted.

**Comment by keithdadkins** [comment]
> Great work finding all that!
> 
> But could you please only keep the Ansible + Terrraform commit? All the commits that yank sample resources should be dropped/reverted.
Done. And thanks for looking at this!

**Review by njdister — APPROVED** [review]
This covers everything I can find within the ops folder, nice job!

**Review by jzulim — APPROVED** [review]
LGTM. Thorough and complete. 

p.s. Do we have to update any SecCom docs to signal this connection has been broken down?

**Pull request merged**
