### PR TITLE
BFD-3464: Add data dictionary to static site

### PR DESCRIPTION
**Pull request by aschey-forpeople**
**JIRA Ticket:**
[BFD-3464](https://jira.cms.gov/browse/BFD-3464)

**User Story or Bug Summary:**

---

### What Does This PR Do?

Adds the initial scaffolding for the static site and includes a rough draft for including the data dictionary as a static table.
It will be worth doing some refactoring for best practices on how to organize the content here with Jekyll (inline css, etc) but it's a start.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [x] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mjburling — CHANGES_REQUESTED** [review]
What we've seen in the demo has been great. Thanks for putting this together, Austin!

Obviously, the static-site doesn't yet exist, but this provides some really helpful structure to work with.

I'm curious, though. Are we introducing a potential headache for ourselves in producing/storing another copy of the data dictionary? I did a brief diff on what our stored json produces and the copies you've introduced, and they've already drifted. I haven't thought through the implications on a developer experience when we ask anyone to make adjustments to this. Caveats aside, I was thinking we might just exclude the these assets, reuse existing ones, and rely on CI to populate `static-site/_data`, e.g.

```sh
mkdir -p static-site/_data
jq -s '.' apps/bfd-server/bfd-server-docs/data-dictionary/data/V1/*.json > "static-site/_data/data-dictionary-v1.json"
jq -s '.' apps/bfd-server/bfd-server-docs/data-dictionary/data/V2/*.json > "static-site/_data/data-dictionary-v2.json"
```
...and the resultant data json could be smaller still if we were to do a `jq -cs` instead. 

How do you see it?

**Comment by aschey-forpeople** [comment]
> What we've seen in the demo has been great. Thanks for putting this together, Austin!
> ...

Yes, agreed on all counts. The change I made was to replace `\\n` with `\n` so the whitespace renders properly. We'll need to add something to the CI pipeline that copies the data dictionary into the folder and runs that text replacement. I wasn't sure what the CI setup for the static site would look like quite yet so I opted to do it this way as a temporary measure, but if you think the initial CI setup is in scope for this ticket then I can start on that.

**Comment by mjburling** [comment]
> Yes, agreed on all counts.

Rad. You think maybe `.gitignore` needs to be updated to ignore files under `static-site/_data/*`?

> The change I made was to replace `\\n` with `\n` so the whitespace renders properly.

If that were changed in the source material, e.g. the json fragments themselves, I wonder if that has some negative downstream impacts on e.g. the xlsx representation 🤔

**Comment by aschey-forpeople** [comment]
> Rad. You think maybe `.gitignore` needs to be updated to ignore files under `static-site/_data/*`?

If we want to start working on the CI changes in the context of this PR, then yes. If not, we can keep it as is for now I think.

> > The change I made was to replace `\\n` with `\n` so the whitespace renders properly.
> 
> If that were changed in the source material, e.g. the json fragments themselves, I wonder if that has some negative downstream impacts on e.g. the xlsx representation 🤔

We can certainly try it and see. I'm not sure if it was done this way to prevent the actual newlines from making the xlsx rows from getting too large or maybe it's just an artifact of whatever is generating the final output.

**Comment by aschey-forpeople** [comment]
Took a look and the `\\n`s are present in the source json files. I think we can probably remove them as part of the data dictionary generation process.

**Comment by aschey-forpeople** [comment]
Tried it out, unescaping the newlines does actually cause the json to render as formatted in the xlsx. But maybe that's better? It's pretty ugly in its current state.

Before:
image

After:
image

**Comment by aschey-forpeople** [comment]
Scratch that - it also makes the newlines render in the csv so that the csv is no longer valid so that's not gonna work.

**Review by sb-benohe — APPROVED** [review]
overall LGTM, just a note about Jekyll-> 

`Jekyll developer Frank Taillandier said that the Jekyll codebase "is in frozen mode and permanent hiatus" and recommended users whose needs are not met by the frozen state of Jekyll move to Eleventy`

**Review by mjburling — APPROVED** [review]

**Pull request merged**
