### PR TITLE
Synthetic script

### PR DESCRIPTION
**Pull request by cbrunefearless**
### Change Details

Script to grab synthetic benes and run it against EOB, Patient, and Coverage Endpoints

### Acceptance Validation

Script to grab synthetic benes and run it against EOB, Patient, and Coverage Endpoints.  Make sure no security data is stored and the right synthetic benes are being pulled

### Feedback Requested

Script to grab synthetic benes and run it against EOB, Patient, and Coverage Endpoints.  Make sure no security data is stored and the right synthetic benes are being pulled
### External References

- [BFD-605](https://jira.cms.gov/browse/BFD-605)

### Security Implications

- [ ] new software dependencies

N/A
- [ ] altered security controls

N/A
- [ ] new data stored or transmitted

N/A
- [ ] security checklist is completed for this change

N/A
- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by jzulim** [comment]
@keithdadkins - I think you might be very well suited to give this script a review. tag! :)

**Comment by njdister** [comment]
@cbrunefearless It might be good to use switches via getopt or even just flags after the script to run part 1 or 2 instead of having to comment out blocks of code:

Flags:
```
./synthetic_endpoint_response.sh part1

if [ "$1" == "part1" ]; then
    (run part 1)
elif [ "$1" == "part2" ]; then
    (run part 2)
fi
```

Getopt is a bit more involved, but fancy: https://dustymabe.com/2013/05/17/easy-getopt-for-a-bash-script/

**Comment by keithdadkins** [comment]
Another tip, install and run `shellcheck` (`brew install shellcheck`) to help lint and find security issues with bash scripts.

**Review by keithdadkins — APPROVED** [review]
OK for a one off script as long as it gets the job done. But the script itself could use some refactoring (like taking advantage of functions and args instead of depending on commenting out code).

**Review by jzulim — APPROVED** [review]
If we need this script again, we can refactor it a bit. However, it works. :) TY.

**Pull request merged**
