### PR TITLE
[BFD-772] Provision custom reader endpoints for mitre

### PR DESCRIPTION
**Pull request by keithdadkins**
### Change Details
This PR creates two new custom database reader endpoints so we can isolate Mitre's database load (reads) from our production cluster. It makes use of a module dedicated for this work. 

Once the module is enabled and the terraform applied, it will provision two custom database reader endpoints. One endpoint will point to a single reader node (the "beta" reader node for mitre), and one endpoint will round-robin between the remaining reader nodes. Note, an "endpoint" in this context is essentially custom DNS entries for our database.

### This PR will need to be done in stages. 

- [x] The first stage will be to get a thumbs up to provision the custom reader endpoints (this is a non-destructive operation that only adds the custom endpoints.. see the terraform plan below). This happens once beta_reader goes from false to true. I will keep this PR in draft for this part.
- [x] Once the new endpoints are provisioned, I will update this PR with a commit that points our app servers to to the new "bfd-prod-ro"  endpoint and will submit this PR for a final review. 
- [ ]  Once approved and merged, I will deploy so the changes take effect.

#### teerraform plan for the custom endpoints

The following terraform will be applied. Note that the "static_members" dictate which nodes get traffic for that endpoint. 

The beta reader is dynamically assigned the last reader node in the cluster (`bfd-prod-aurora-cluster-node-3`).

The other custom endpoint, the one our app servers will use, will round-robin requests to all remaining reader nodes. This is `bfd-prod-aurora-cluster-node-0` and `bfd-prod-aurora-cluster-node-2. Since `bfd-prod-aurora-cluster-node-1` is the writer node, it will not be used (because of `custom_endpoint_type = "READER"`).

```terraform
Terraform will perform the following actions:

  # module.stateful.module.aurora.aws_rds_cluster_endpoint.beta_reader[0] will be created
  + resource "aws_rds_cluster_endpoint" "beta_reader" {
      + arn                         = (known after apply)
      + cluster_endpoint_identifier = "bfd-prod-beta-reader"
      + cluster_identifier          = "bfd-prod-aurora-cluster"
      + custom_endpoint_type        = "READER"
      + endpoint                    = (known after apply)
      + id                          = (known after apply)
      + static_members              = [
          + "bfd-prod-aurora-cluster-node-3",
        ]
    }

  # module.stateful.module.aurora.aws_rds_cluster_endpoint.readers[0] will be created
  + resource "aws_rds_cluster_endpoint" "readers" {
      + arn                         = (known after apply)
      + cluster_endpoint_identifier = "bfd-prod-ro"
      + cluster_identifier          = "bfd-prod-aurora-cluster"
      + custom_endpoint_type        = "READER"
      + endpoint                    = (known after apply)
      + excluded_members            = [
          + "bfd-prod-aurora-cluster-node-3",
        ]
      + id                          = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### External References

- [BFD-772](https://jira.cms.gov/browse/BFD-772)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by jzulim** [comment]
👍

**Comment by keithdadkins** [comment]
custom endpoints have been provisioned and app configs updated

**Review by njdister — APPROVED** [review]
Verified vault is looking as expected 👍

**Review by jzulim — APPROVED** [review]
Decrypted vault, looks good.

**Pull request merged**
