### PR TITLE
BFD-3201: Remediate CCW Duplicate Benes

### PR DESCRIPTION
**Pull request by mackec1**
**JIRA Ticket:**
[BFD-123456](https://jira.cms.gov/browse/BFD-3201)

**User Story or Bug Summary:**
CCW over the past 4 months provided Beneficiary records that have a null MBI_NUM; this was due to some crossed wires at their end when matching BENE_LINK_KEY values. This resulted in thousands of records in the BFD database where an actual beneficiary (a person) has two records.

### What Does This PR Do?
This PR attempts to cleanup duplicate records provided by CCW; as such, CCW looked into theor internal processing, found the issue, and performed a bug fix. As part of that effort, they have provided a CSV file that contains a list of BENE_ID values that they believe have multiple records.

This PR contains a bash script that invokes PSQL to perform the cleanup:

- FHIR_XRefed_BENE_ID.csv file is loaded into a temp table, CCW_DUPL_BENE_FROM_CSV
- backup of data that is to be deleted:
  - BENEFICIARIES ->  BENEFICIARIES_CCW_REMEDIATION
  - BENEFICIARIES_HISTORY -> BENEFICIARIES_HISTORY_CCW_REMEDIATION
  - BENEFICIARY_MONTHLY - > BENEFICIARY_MONTHLY_CCW_REMEDIATION
- deletes duplicate data from:
  - BENEFICIARIES
  - BENEFICIARIES_HISTORY
  - BENEFICIARY_MONTHLY

Some post-cleanup analysis will need to be performed to ensure the efficacy of the CCW-provided list vs. our database.

**NOTE:**

The CCW list has 61,,855 records; previous analysis of the BFD db showed that we have (had) around 56k duplicates. Thus, staying on the conservative side, we'll **ONLY DELETE** records with null MBI_NUM. Some further analysis using the CCW-provided list may yield more candidates for cleanup.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:
* efficacy and correctness of the script
* any glaring holes or gotcha's tat make running this script dangerous.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [ X I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] The data dictionary has been updated with any field mapping changes, if any were made.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by dondevun — DISMISSED** [review]
lgtm

**Review by brandoncruz3 — APPROVED** [review]

**Review by keithdadkins — CHANGES_REQUESTED** [review]
Could you inject a prompt to continue somewhere? Just so you can double check things before pulling the trigger?

**Comment by keithdadkins** [comment]
> Could you inject a prompt to continue somewhere? Just so you can double check things before pulling the trigger?

Otherwise, everything looks good to me. Well documented, cautious, flexible.

**Review by dondevun — APPROVED** [review]

**Review by keithdadkins — APPROVED** [review]
Thanks!

**Review by brandoncruz3 — APPROVED** [review]

**Pull request merged**
