### PR TITLE
BFD-2449: Enable IAM role authentication to RDS clusters

### PR DESCRIPTION
**Pull request by keithdadkins**
**JIRA Ticket:**
[BFD-2449](https://jira.cms.gov/browse/BFD-2449)

**User Story or Bug Summary:**

As an Aurora/RDS security best-practice, we should use IAM to authenticate database access.

---

### What Does This PR Do?

Enables users to connect to our db clusters using IAM auth instead of static passwords and adds a psql.sh script useful for testing.

IAM database auth with Aurora doesn't support global conditions in policies. This limits our ability to cleanly restrict access using things like Principal/Request tags (ie [ABAC](https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_attribute-based-access-control.html)). Instead, we are creating a "fhirdb auth" role for each of the primary established environments (ie. prod, prod-sbx, test), and using associated IAM groups to control who is allowed to assume the role. See the [Aurora IAM docs here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html).

Please note that this is **_not the only layer of security_**. In addition to a user belonging to an IAM group, a matching postgres user - with the same name - must be added to each cluster, granted the special `rds_iam` role, along with any other postgres permissions as normal. This work, along with associated utilities for managing this process, will be forthcoming in BFD-2448.

Hopefully, AWS will add Global Conditions support for the `rds-db:connect` action so we can make this a bit cleaner.

#### psql.sh test script notes
This is something that I hacked together and is not the util I have envisioned for us to use, but it should work to help you verify if you so choose.

To use it:

1. `cd ops/utils/database-auth`
2. `wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem`
3. `./psql.sh -e test -a $BFDACCTNUM -H $ATESTCLUSTERENDPOINT) -x "-c select count(*) from schema_version"`

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

I've tried my best to implement least-priv here, but I could not find a clean way to escape a few wildcards. Also, a full AWS admin would be able to assume any role they choose, so they would circumvent the group policy. Something we could potentially address in the future.

Again though, this is not the only layer of security as a matching database user must exist in the database and be granted any postgres permission as usual. I also prevent an IAM user from authenticating as a different IAM user.

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [x] Yes
      * [ ] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    4. There isn't too much of a burden on reviewers.
    5. Any problems it causes have a small "blast radius".
    6. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by keithdadkins** [comment]
I tested this with @JeremyIR in an ephemeral cluster, but I still need to add all of our users all the others. Ping me if you want to test before I get to it and I'll get you added.

**Review by StewGoin — DISMISSED** [review]
This seems like a good improvement to me.

**Review by JeremyIR — DISMISSED** [review]

**Comment by keithdadkins** [comment]
I refactored this a bit so that each db auth role can only connect to associated clusters. While this would limit the amount of seeds per environment to 9, I think that's reasonable.

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by mjburling — APPROVED** [review]

**Pull request merged**
