### PR TITLE
BFD-523: Fix operation name issues, particularly with _lastUpdated requests

### PR DESCRIPTION
**Pull request by karlmdavis**
### Change Details

Resolve operation name bugs, including with `_lastUpdated` requests:

1. Fix operation name bug for Coverage search. The call to `publishOperationName()` has to be last or the options set won't actually take effect.
2. Fix operation name bugs in Patient?_id= searches. The operation name wasn't being set **at all** when `_lastUpdated` filtering triggered such that no results would be returned. This likely led to some of the generic (i.e. not useful) operation name entries seen in our logs.
3. Add `_lastUpdated=[true|false]` to operation names. This was not previously being included in operation names, which really reduces the usefulness of our logs for performance measurement purposes.

### Acceptance Validation

1. Are these fixes correct?
2. Are these fixes complete: are there any other operation name issues that also ought to be addressed now?

### Feedback Requested

(See above.)

### External References

- [BLUEBUTTON-523](https://jira.cms.gov/browse/BFD-523)

### Security Implications

No security implications are indicated for this PR:

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by dshekhar18 — DISMISSED** [review]
Good stuff to better help with monitoring! Thanks @karlmdavis for taking this up!

**Review by jzulim — DISMISSED** [review]
Makes sense to me. Thank you for this fix.

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by jzulim — APPROVED** [review]
LGTM

**Pull request merged**
