### PR TITLE
Format existing terraform code to meet Terraform language conventions.

### PR DESCRIPTION
**Pull request by keithdadkins**
This is the result of running `terraform fmt -recursive`. The `terraform fmt` command rewrites terraform code to a canonical format and style to match Terraform's language conventions.

In other words, this gets rid of all the crazy spaces, tabs, and inconsistent formatting found in our terraform code base.

Going forward, this command should be run before committing new or updated terraform configs.

### Change Details
Changes terraform spacing/code formatting throughout our codebase.

### Acceptance Validation
Only formatting changes with NO changes to the code itself.

### External References

- [BFD-653](https://jira.cms.gov/browse/BFD-653)

### CODE REVIEW

**Comment by jzulim** [comment]
@keithdadkins Do you think we should test run this TF and deploy to TEST before merging?

**Comment by keithdadkins** [comment]
> @keithdadkins Do you think we should test run this TF and deploy to TEST before merging?

I do not think it is necessary honestly. I ran `terraform validate` in every folder as well as `terraform plan` (which does validation as well) in multiple environments. I also reviewed each file's diff one by one and did not see anything that concerned me. So between validation, plans, and manual reviews, I believe this is a simple and safe commit.

**Review by jzulim — APPROVED** [review]
LGTM

**Review by njdister — APPROVED** [review]
Nice work making TF more consistent everywhere, passes all validation in each environment so LGTM.

**Pull request merged**
