### PR TITLE
BFD-549 - Set jpa property to none

### PR DESCRIPTION
**Pull request by cbrunefearless**
### Change Details
 Have to disable the setting .HBM2DDL_AUTO to none in a separate PR before the schema change, If you don't, and the app hits any auto-scaling events will cause the app to do bad things.

### External References

- [BFD-549](https://jira.cms.gov/browse/BFD-549)

### Security Implications

Sets the jpa entity property to NONE

- [ ] new software dependencies
n/a

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by karlmdavis — CHANGES_REQUESTED** [review]
Thanks for putting this cute little PR together, Chris!

Could you please, though, explain why this is being done in the PR and/or commit message and/or a code comment? We had a bad time with PRs that had no explanation a while back, and it's best to avoid doing that, going forwards.

**Comment by cbrunefearless** [comment]
> Thanks for putting this cute little PR together, Chris!
> 
> Could you please, though, explain why this is being done in the PR and/or commit message and/or a code comment? We had a bad time with PRs that had no explanation a while back, and it's best to avoid doing that, going forwards.

done in the change details in the PR

**Review by karlmdavis — APPROVED** [review]
LGTM

**Review by jzulim — APPROVED** [review]
LGTM, thanks for the additional details in the PR description.

**Pull request merged**
