### PR TITLE
BCDA-3872 - Implement service-date filter on EOB resources

### PR DESCRIPTION
**Pull request by mtrang1263**
### Change Details

1. Add new optional query parameter (`service-date`) for EOB resource types. Implementation based on [RFC for serviceDate filter](https://github.com/CMSgov/beneficiary-fhir-data/pull/376).
2. Updating EOB integration tests to verify service-date filtering capabilities.

### Acceptance Validation

1. CI passes.
2. Deploy to testing environment to verify behavior.

### External References

- [BCDA-3872](https://jira.cms.gov/browse/BCDA-3872)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [x] new data stored or transmitted

Adding new optional query parameter that may affect the data that is returned to the caller.

- [x] security checklist is completed for this change[
Security checklist](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BCDA&title=20-10-16%3A+Service+Date+Filter+Implementation+Security+Checklist) created for this change.

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by cbrunefearless — APPROVED** [review]
LGTM

**Review by cbrunefearless — DISMISSED** [review]
LGTM

**Review by dshekhar18 — COMMENTED** [review]
@mtrang1263 Solid work! Will service-date filter available for all partners? If this is specific to BCDA needs, then this needs to used with BCDA Partner specific flag.

**Comment by jzulim** [comment]
@mtrang1263 - Great work on this. If you wouldn't mind taking a look at this PR, where Karl is fixing a missing logging / metrics issue with our last query parameter we added _lastupdated, you'll want to do something similar so that when calls are made with this operation we log it correctly. See here and reach out to us if you have questions. https://github.com/CMSgov/beneficiary-fhir-data/pull/392

**Review by dshekhar18 — DISMISSED** [review]
Good work! Service-Date EOB search param is used to filter the data based on the date of service, to ensure that BCDA is not returning beneficiary data to an ACO to which that beneficiary is NOT attributed.

**Review by jzulim — APPROVED** [review]
Looks good. Ran VERY basic performance tests with and without service date. As expected, the use of service date has the potential to reduce the payload size and therefore response time. Test coverage sufficient. Documentation included. Approved.

**Review by dshekhar18 — APPROVED** [review]
Solid job!!

**Pull request merged**
