### PR TITLE
Aurora test resources in TF

### PR DESCRIPTION
**Pull request by jzulim**
Draft PR

Changes:
- Adds new logs bucket for Aurora resource testing (lb, etc.) 
- Adds new ETL bucket for Aurora resource testing 
- Adjust parameter group 'import_mode' for postgres 11.6
- Adds aurora-etl bucket to etl-rw IAM policy
- Creates 2 Aurora cluster instances (master and replica) 
- Creates Aurora Cluster 
- Creates Aurora LB
- Creates Aurora ASG

Note:
Need to first apply stateful resources locally (as Jenkins does not currently deploy these changes) 
Afterwards, test deploy this branch to the TEST env.

### CODE REVIEW

**Comment by jzulim** [comment]
Stateful Resources

```An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.stateful.aws_db_parameter_group.import_mode must be replaced
-/+ resource "aws_db_parameter_group" "import_mode" {
      ~ arn         = "arn:aws:rds:us-east-1:577373831711:pg:bfd-test-import-mode-parameter-group" -> (known after apply)
        description = "Sets parameters that optimize bulk data imports"
      ~ family      = "postgres9.6" -> "postgres11.6" # forces replacement
      ~ id          = "bfd-test-import-mode-parameter-group" -> (known after apply)
        name        = "bfd-test-import-mode-parameter-group"
      + name_prefix = (known after apply)
      - tags        = {} -> null

        parameter {
            apply_method = "immediate"
            name         = "autovacuum"
            value        = "0"
        }
        parameter {
            apply_method = "immediate"
            name         = "checkpoint_timeout"
            value        = "1800"
        }
        parameter {
            apply_method = "immediate"
            name         = "log_connections"
            value        = "1"
        }
        parameter {
            apply_method = "immediate"
            name         = "maintenance_work_mem"
            value        = "4194304"
        }
        parameter {
            apply_method = "immediate"
            name         = "synchronous_commit"
            value        = "off"
        }
        parameter {
            apply_method = "pending-reboot"
            name         = "max_wal_size"
            value        = "256"
        }
        parameter {
            apply_method = "pending-reboot"
            name         = "wal_buffers"
            value        = "8192"
        }
    }

  # module.stateful.aws_iam_policy.etl_rw_s3 will be updated in-place
  ~ resource "aws_iam_policy" "etl_rw_s3" {
        arn         = "arn:aws:iam::577373831711:policy/bfd-test-etl-rw-s3"
        description = "ETL read-write S3 policy"
        id          = "arn:aws:iam::577373831711:policy/bfd-test-etl-rw-s3"
        name        = "bfd-test-etl-rw-s3"
        path        = "/"
      ~ policy      = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "kms:Decrypt",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:kms:us-east-1:577373831711:key/7dcca42a-da93-40b1-a4a8-2eb10050f449",
                        ]
                      - Sid      = "ETLRWKMS"
                    },
                  - {
                      - Action   = [
                          - "s3:ListBucket",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:s3:::bfd-test-etl-577373831711",
                        ]
                      - Sid      = "ETLRWBucketList"
                    },
                  - {
                      - Action   = [
                          - "s3:GetObject",
                          - "s3:PutObject",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:s3:::bfd-test-etl-577373831711/*",
                        ]
                      - Sid      = "ETLRWBucketActions"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
    }

  # module.stateful.aws_rds_cluster.default will be created
  + resource "aws_rds_cluster" "default" {
      + apply_immediately               = false
      + arn                             = (known after apply)
      + availability_zones              = [
          + "us-east-1a",
          + "us-east-1b",
          + "us-east-1c",
        ]
      + backup_retention_period         = 1
      + cluster_identifier              = "bfd-test"
      + cluster_identifier_prefix       = (known after apply)
      + cluster_members                 = (known after apply)
      + cluster_resource_id             = (known after apply)
      + copy_tags_to_snapshot           = true
      + database_name                   = "bfdtemp"
      + db_cluster_parameter_group_name = "bfd-test-import-mode-parameter-group"
      + db_subnet_group_name            = "bfd-test-subnet-group"
      + deletion_protection             = false
      + enabled_cloudwatch_logs_exports = [
          + "audit",
          + "error",
          + "general",
          + "slowquery",
          + "postgresql",
        ]
      + endpoint                        = (known after apply)
      + engine                          = "aurora-postgresql"
      + engine_mode                     = "provisioned"
      + engine_version                  = "11.6"
      + hosted_zone_id                  = (known after apply)
      + id                              = (known after apply)
      + kms_key_id                      = "arn:aws:kms:us-east-1:577373831711:key/7dcca42a-da93-40b1-a4a8-2eb10050f449"
      + master_password                 = (sensitive value)
      + master_username                 = "bfduser"
      + port                            = 5432
      + preferred_backup_window         = "05:00-06:00"
      + preferred_maintenance_window    = "fri:07:00-fri:08:00"
      + reader_endpoint                 = (known after apply)
      + skip_final_snapshot             = false
      + storage_encrypted               = true
      + tags                            = {
          + "Environment" = "test"
          + "Layer"       = "data"
          + "application" = "bfd"
          + "business"    = "oeda"
          + "stack"       = "test"
        }
      + vpc_security_group_ids          = [
          + "sg-04d406660d1da0d6b",
          + "sg-06296860a8f763227",
          + "sg-0a1a9d02fe5ac3891",
          + "sg-0ac1ebd5e7c3dd04b",
        ]
    }

  # module.stateful.aws_rds_cluster_instance.cluster_instances[0] will be created
  + resource "aws_rds_cluster_instance" "cluster_instances" {
      + apply_immediately               = (known after apply)
      + arn                             = (known after apply)
      + auto_minor_version_upgrade      = true
      + availability_zone               = (known after apply)
      + cluster_identifier              = (known after apply)
      + copy_tags_to_snapshot           = false
      + db_parameter_group_name         = (known after apply)
      + db_subnet_group_name            = (known after apply)
      + dbi_resource_id                 = (known after apply)
      + endpoint                        = (known after apply)
      + engine                          = "aurora"
      + engine_version                  = (known after apply)
      + id                              = (known after apply)
      + identifier                      = "aurora-cluster-demo-0"
      + identifier_prefix               = (known after apply)
      + instance_class                  = "db.r5.24xlarge"
      + kms_key_id                      = (known after apply)
      + monitoring_interval             = 0
      + monitoring_role_arn             = (known after apply)
      + performance_insights_enabled    = (known after apply)
      + performance_insights_kms_key_id = (known after apply)
      + port                            = (known after apply)
      + preferred_backup_window         = (known after apply)
      + preferred_maintenance_window    = (known after apply)
      + promotion_tier                  = 0
      + publicly_accessible             = false
      + storage_encrypted               = (known after apply)
      + writer                          = (known after apply)
    }

  # module.stateful.aws_rds_cluster_instance.cluster_instances[1] will be created
  + resource "aws_rds_cluster_instance" "cluster_instances" {
      + apply_immediately               = (known after apply)
      + arn                             = (known after apply)
      + auto_minor_version_upgrade      = true
      + availability_zone               = (known after apply)
      + cluster_identifier              = (known after apply)
      + copy_tags_to_snapshot           = false
      + db_parameter_group_name         = (known after apply)
      + db_subnet_group_name            = (known after apply)
      + dbi_resource_id                 = (known after apply)
      + endpoint                        = (known after apply)
      + engine                          = "aurora"
      + engine_version                  = (known after apply)
      + id                              = (known after apply)
      + identifier                      = "aurora-cluster-demo-1"
      + identifier_prefix               = (known after apply)
      + instance_class                  = "db.r5.24xlarge"
      + kms_key_id                      = (known after apply)
      + monitoring_interval             = 0
      + monitoring_role_arn             = (known after apply)
      + performance_insights_enabled    = (known after apply)
      + performance_insights_kms_key_id = (known after apply)
      + port                            = (known after apply)
      + preferred_backup_window         = (known after apply)
      + preferred_maintenance_window    = (known after apply)
      + promotion_tier                  = 0
      + publicly_accessible             = false
      + storage_encrypted               = (known after apply)
      + writer                          = (known after apply)
    }

  # module.stateful.module.etl-aurora.aws_s3_bucket.main will be created
  + resource "aws_s3_bucket" "main" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "bfd-test-etl-aurora-577373831711"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Environment" = "test"
          + "Layer"       = "data"
          + "application" = "bfd"
          + "business"    = "oeda"
          + "role"        = "etl-aurora"
          + "stack"       = "test"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + logging {
          + target_bucket = "bfd-test-logs-577373831711"
          + target_prefix = "etl-aurora_s3_access_logs"
        }

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + kms_master_key_id = "arn:aws:kms:us-east-1:577373831711:key/7dcca42a-da93-40b1-a4a8-2eb10050f449"
                  + sse_algorithm     = "aws:kms"
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # module.stateful.module.etl-aurora.aws_s3_bucket_public_access_block.main will be created
  + resource "aws_s3_bucket_public_access_block" "main" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = false
      + restrict_public_buckets = false
    }

  # module.stateful.module.logs-aurora.aws_s3_bucket.main will be created
  + resource "aws_s3_bucket" "main" {
      + acceleration_status         = (known after apply)
      + acl                         = "log-delivery-write"
      + arn                         = (known after apply)
      + bucket                      = "bfd-test-logs-aurora-577373831711"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Environment" = "test"
          + "Layer"       = "data"
          + "application" = "bfd"
          + "business"    = "oeda"
          + "role"        = "logs-aurora"
          + "stack"       = "test"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + sse_algorithm = "AES256"
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # module.stateful.module.logs-aurora.aws_s3_bucket_public_access_block.main will be created
  + resource "aws_s3_bucket_public_access_block" "main" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = false
      + restrict_public_buckets = false
    }

Plan: 8 to add, 1 to change, 1 to destroy.```

**Comment by njdister** [comment]
I've refactored this PR so that the stateless resources specific to the aurora demo phase have their own backend as not to be deployed on every Jenkins run.

**Comment by njdister** [comment]
My current suggestion would be that this branch is only used for testing and NOT MERGED!  Final implementation should happen in a separate branch and all terraform resources created in this branch be destroyed prior to closing this PR out.

**Comment by njdister** [comment]
This PR is no longer needed for the final Aurora implementation, closing

**Pull request closed without merging**
