### PR TITLE
BB2-2190: Terraform BB2 BFD-Insights components part1

### PR DESCRIPTION
**Pull request by dtisza1**
**JIRA Ticket:**
[BB2-2190](https://jira.cms.gov/browse/BB2-2190)

**User Story or Bug Summary:**

Terraforming the **current** configuration of BB2 components for BFD Insights. This is in order to better manage resources and to preserve configuration in the event of a "disaster".

This includes Terraform for the part 1 (of 3) related Jira stories. Will create PRs for those after this one is reviewed. A preview of those changes are in the DRAFT PR [here](https://github.com/CMSgov/beneficiary-fhir-data/pull/1777).

#### NOTES:

-  Developing using the `test` workspace until this PR reviewed & approved. Afterward, will apply to `impl` and `prod` enviornments.
- The resources are imported in to the states for the `test,impl, prod` workspaces currently.
  - The `test` workspace has changes applied and matching the plan.
  - The `impl` and `prod` workspaces are showing expected changes, such as default tags and some others.
    - These changes will be applied after PR review is complete!

#### The following is a summary of work done for this PR:

- Setup `default_tags` per Keith's example with:
  - business = "OEDA"
  - application = "bfd-insights"
  - project = "bb2"
  - Environment = "<test/impl/prod/allenv>"
  - stack = "bfd-insights-bb2-<test/impl/prod/allenv>"

- Terraformed the following log stream related components under `bb2/services/log_stream`:
  - Uses Terraform workspaces: `test/impl/prod`
  - Default state key:  bfd-insights/bb2/services/log_stream/terraform.tfstate
  - Resources managed under `modules/cwl_destination`:
    - resource "aws_cloudwatch_log_destination" "cwl_destination"
    - resource "aws_iam_role" "cwl2firehose_role"
    - resource "aws_cloudwatch_log_destination_policy" "cwl_destination_policy"
  - Resource managed under `modules/firehose`:
    - resource "aws_kinesis_firehose_delivery_stream" "kinesis_firehose_stream"
  - Resource managed under `modules/glue_crawler`:
    - resource "aws_glue_crawler" "glue_crawler"

- Improved permissions for the `cwl2firehose_role` in `modules.cwl_destination.main.tf
  - Changed the `inline_policy` action's `Resource`:
    - FROM:
    ```
    Resource = ["arn:aws:firehose:us-east-1:${local.account_id}:*"]
    ```
    - TO:
    ```
    Resource = ["arn:aws:firehose:us-east-1:${local.account_id}:deliverystream/${local.full_name}"]
    ```
  - NOTE: After applying to the `test` environment, verified that logs from BB2 are still flowing OK.
  
- Created a top level `README.md` with overview and usage instruction.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] The data dictionary has been updated with any field mapping changes, if any were made.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mjburling — COMMENTED** [review]
This is pretty simple and in-line with what had discussed. Looking good!

1. We have it in mind to solve for terraform formatting on our behalf in the future... for the time being, we'll have to do it ourselves. Could you be sure to run `terraform fmt` on the modules here?
2. Just a thought toward future automation... it _shouldn't_ be a problem to support a `/bb2` SSM Parameter Store _project hierarchy_ in the BFD account (with appropriate permissions for r/w access for contributors and automation alike) where we might store bb2-specific configuration. Off-the-cuff, perhaps `/bb2/mgmt/common/sensitive/aws_account` or similar? Perhaps not here, but in the near-term, what would you think about moving away from the tfvars from the BB2 account?

**Comment by dtisza1** [comment]
@mjburling I just updated the formatting. I also created a few backlog stories in Jira:  [BB2-2498](https://jira.cms.gov/browse/BB2-2498) and [BB2-2499](https://jira.cms.gov/browse/BB2-2499).  

Thank you!

**Review by mjburling — APPROVED** [review]
This tracks and I'm Excited to see more!

Thank you for your contributions and patience with the process.

**Review by oragame — APPROVED** [review]
This looks great, Dave! Nice work.

**Pull request merged**
