### PR TITLE
BFD-332: Pin JDK 1.8.0.252 for GitHub CI, last known working version.

### PR DESCRIPTION
**Pull request by jzulim**
### Change Details

Our GitHub Actions that power our CI (integration tests in this case) are failing. Looking back at the most recent successful checks and seeing JDK version 1.8.0.252 in github actions workflow scripts was successful, while the latest (1.8.0.262) was breaking the AuthenticationIT's intermittently (mostly all the time, for some unknown reason)

This PR also removes the java_version from the matrix logic, as we dont use different nor test on different versions of java. 

### Acceptance Validation

Please check that the GitHub Actions / checks pass with this change and that there are no security concerns with sticking on 1.8.0.252.

### Feedback Requested

Will this break future dependency updates?

### External References

- [BFD-332](https://jira.cms.gov/browse/BFD-332)

### Security Implications

I see no major security updates between 252 and 262. 

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [x] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Comment by njdister** [comment]
Do you know if v262 is actually getting installed onto the app AMIs?  Is it breaking anything there?  Just want to make sure we're not removing a gate for something that will break later on once deployed.

**Comment by jzulim** [comment]
> Do you know if v262 is actually getting installed onto the app AMIs? Is it breaking anything there? Just want to make sure we're not removing a gate for something that will break later on once deployed.

262 is running on our AMI's. I have an action item to manually validate the two failing Auth IT's in BFD PROD a bit later today.

**Comment by jzulim** [comment]
> > Do you know if v262 is actually getting installed onto the app AMIs? Is it breaking anything there? Just want to make sure we're not removing a gate for something that will break later on once deployed.
> 
> 262 is running on our AMI's. I have an action item to manually validate the two failing Auth IT's in BFD PROD a bit later today.

I've just tested against PROD with an invalid cert and no cert present, both failed the request, as I would expect / hope. These two checks are the Auth IT's that are failing during IT's on 262, but work on 252.

**Comment by njdister** [comment]
> > > Do you know if v262 is actually getting installed onto the app AMIs? Is it breaking anything there? Just want to make sure we're not removing a gate for something that will break later on once deployed.
> > 
> > 
> > 262 is running on our AMI's. I have an action item to manually validate the two failing Auth IT's in BFD PROD a bit later today.
> 
> I've just tested against PROD with an invalid cert and no cert present, both failed the request, as I would expect / hope. These two checks are the Auth IT's that are failing during IT's on 262, but work on 252.

If you have a real deployment running on prod with v262 but only ITs are failing I think this is ok as a stopgap.  But potentially presents a false sense of security as the JVM continues to get upgraded on the AMI but not in CI.

**Comment by jzulim** [comment]
> > > > Do you know if v262 is actually getting installed onto the app AMIs? Is it breaking anything there? Just want to make sure we're not removing a gate for something that will break later on once deployed.
> > > 
> > > 
> > > 262 is running on our AMI's. I have an action item to manually validate the two failing Auth IT's in BFD PROD a bit later today.
> > 
> > 
> > I've just tested against PROD with an invalid cert and no cert present, both failed the request, as I would expect / hope. These two checks are the Auth IT's that are failing during IT's on 262, but work on 252.
> 
> If you have a real deployment running on prod with v262 but only ITs are failing I think this is ok as a stopgap. But potentially presents a false sense of security as the JVM continues to get upgraded on the AMI but not in CI.
> 
> Edit: I forgot to ask, what version of the JVM is running on the Jenkins instance that produces JAR/WAR files?

Jenkins is running 242. @keithdadkins is working to update Jenkins, and as part of that I suspect we'll need to be cognizant of this, should we bump Jenkins to 262, our Build Apps stage might begin to fail as well.

**Comment by jzulim** [comment]
> > > > > Do you know if v262 is actually getting installed onto the app AMIs? Is it breaking anything there? Just want to make sure we're not removing a gate for something that will break later on once deployed.
> > > > 
> > > > 
> > > > 262 is running on our AMI's. I have an action item to manually validate the two failing Auth IT's in BFD PROD a bit later today.
> > > 
> > > 
> > > I've just tested against PROD with an invalid cert and no cert present, both failed the request, as I would expect / hope. These two checks are the Auth IT's that are failing during IT's on 262, but work on 252.
> > 
> > 
> > If you have a real deployment running on prod with v262 but only ITs are failing I think this is ok as a stopgap. But potentially presents a false sense of security as the JVM continues to get upgraded on the AMI but not in CI.
> > Edit: I forgot to ask, what version of the JVM is running on the Jenkins instance that produces JAR/WAR files?
> 
> Jenkins is running 242. @keithdadkins is working to update Jenkins, and as part of that I suspect we'll need to be cognizant of this, should we bump Jenkins to 262, our Build Apps stage might begin to fail as well.

To make matters more dijointed, our CentOS7 docker containers are running 252, and when I try and check for updates in the CentOS repo's, it reports no updates at this time for this package. 🤷

**Pull request merged**
