### PR TITLE
BFD-2556: Default CCW pipeline to idempotency mode

### PR DESCRIPTION
**Pull request by cbrunefearless**
**JIRA Ticket:**
[BFD-2556](https://jira.cms.gov/browse/BFD-2556)

**User Story or Bug Summary:**

User Story
As an operations engineer, I want the CCW RIF Loader to run with idempotence by default so that I can avoid reconfiguration when the RIF loader is interrupted.

Background
The BFD ETL Pipeline Job is currently configured to run without idempotence mode. While this provides a modest performance improvement over the additional checks that are party to idempotence, these performance gains pale in comparison to the more recent performance improvements introduced as part of [BFD-2508](https://jira.cms.gov/browse/BFD-2508) and [BFD-2509](https://jira.cms.gov/browse/BFD-2509).

In the event of intended or unintended interruptions to the pipeline due to availability, data discrepancies, or other issues, operations engineers must introduce temporary adjustments to the running configuration before restarting the pipeline in order to request idempotence mode–we can eliminate this part of the recovery process and avoid costly (time-intensive) mistakes where the pipeline has been started in a non-idempotent mode when idempotence is required.

AC
CCW RIF Loader Pipeline Jobs are configured with idempotency
Application Defaults are adjusted to default to idempotency

---

### What Does This PR Do?

Changes the yaml defaults for ssm parameter data_pipeline_idempotency_required to true to run idempotency mode

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] The data dictionary has been updated with any field mapping changes, if any were made.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mjburling — COMMENTED** [review]
OK! This solves for the first criterion, but I'm curious about the second–the second was added to target the application-level, internal defaults, but I _think_ this was done without the full awareness that it's currently encoded as a required environment variable rather than an optional that defaults to `false`. As a result, I think we might want to go ahead and remove that second item from the AC. Would you agree?

**Comment by lsmitchell** [comment]
I guess here's a question I should have asked whenever this was being formulated, but do we ever want to turn this _off_ now? Should the flag just be removed?

**Comment by cbrunefearless** [comment]
> OK! This solves for the first criterion, but I'm curious about the second–the second was added to target the application-level, internal defaults, but I _think_ this was done without the full awareness that it's currently encoded as a required environment variable rather than an optional that defaults to `false`. As a result, I think we might want to go ahead and remove that second item from the AC. Would you agree?

I agree!!

**Comment by cbrunefearless** [comment]
> I guess here's a question I should have asked whenever this was being formulated, but do we ever want to turn this _off_ now? Should the flag just be removed?

I feel like we still want to flexibility "just in case"

**Review by lsmitchell — APPROVED** [review]

**Review by mjburling — APPROVED** [review]

**Pull request merged**
