### PR TITLE
[Snyk] Upgrade org.flywaydb:flyway-core from 9.16.1 to 9.20.0

### PR DESCRIPTION
**Pull request by albertico-gov**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade org.flywaydb:flyway-core from 9.16.1 to 9.20.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **10 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-06-20.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/bluebutton-fd-oeda/project/9de3065d-eca5-437e-8a68-248db303c197?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/bluebutton-fd-oeda/project/9de3065d-eca5-437e-8a68-248db303c197/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/bluebutton-fd-oeda/project/9de3065d-eca5-437e-8a68-248db303c197/settings/integration?pkg&#x3D;org.flywaydb:flyway-core&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by brianburton — APPROVED** [review]

**Comment by brianburton** [comment]
Interesting here that it chose 9.20.0 when there is already a 9.20.1 and a 9.21.1.

**Review by brianburton — CHANGES_REQUESTED** [review]
Maven verify failed in the migrator test so this may not be compatible.  Maybe we need a different version.

**Comment by mjburling** [comment]
> Maven verify failed in the migrator test so this may not be compatible. Maybe we need a different version.

Noted. Moving this into DRAFT until we have time to assess what's going wrong. Thanks!

**Comment by keithdadkins** [comment]
https://github.com/CMSgov/beneficiary-fhir-data/pull/1878

**Pull request closed without merging**
