### PR TITLE
DCGEO-65: Add feature flag implementation

### PR DESCRIPTION
**Pull request by KyRobbins**
### Change Details

Adds a feature flag to allow toggling the serving of Pre Adjudicated claim resources via the fhir API using environment variables passed in as system properties.

### Acceptance Validation

Is the implementation of this feature flag consistent with implementations of similar features?

### Feedback Requested

Are there any areas where this implementation does not fully cover the needs as would be required by such a feature flag?

### External References

- [BFD-65](https://jira.cms.gov/browse/DCGEO-65)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by ericbuckley — APPROVED** [review]
LGTM

**Comment by Gabasol** [comment]
Do we need @brianburton's review on this PR?

**Review by brianburton — DISMISSED** [review]

**Review by ericbuckley — DISMISSED** [review]
👍

**Review by brianburton — DISMISSED** [review]

**Review by cbrunefearless — APPROVED** [review]

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by ericbuckley — APPROVED** [review]

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by rtravitz — APPROVED** [review]
Ship it 👍

**Pull request merged**
