### PR TITLE
BLUEBUTTON-1781: Open prod-sbx to Internet traffic

### PR DESCRIPTION
**Pull request by RickHawesUSDS**
**Why**
To allow developers to continue to test against the latest releases of BFD in their integration tests. See [SIA to open prod-sbx](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BB&title=Update+to+SIA+to+include+request+to+open+prod-sbx+to+general+internet+access+for+developer+usage).

**Changes**
- prod-sbx ELB is replaced and made public.
- The LB security group ingress rule is changed to `0.0.0.0/0`.
- {dpc, mct, bcda, bb}.prod-sbx.bfdcloud.net points to the new ELB.
- ELBs are marked with `prevent_destroy` for safety. 
- No change in other environments

**Deployment Plan**
The change to the prod-sbx ELB cannot be made in-place; It must be destroyed and replaced. This plan deploys without down-time by using a temporary ELB to hold traffic while the main ELB is replaced. Although it may be OK to take down-time in prod-sbx, this plan will be good practice for the next time we have to replace the ELB. 

1. Test current setup while connected by VPN
```
curl --insecure --cert-type pem --cert client_data_server_local_test_env_dpr_keypair.pem  'https://bfd-prod-sbx.bfdcloud.net:443/v1/fhir/metadata?_format=application%2Fjson%2Bfhir'
``` 
2. Setup a `bfd-prod-sbx-temp` ELB by hand using the TF stateless scripts
3. Test new ELB
```
curl --insecure --cert-type pem --cert client_data_server_local_test_env_dpr_keypair.pem  'https://bfd-prod-sbx-fhir-temp-1100214705.us-east-1.elb.amazonaws.com:443/v1/fhir/metadata?_format=application%2Fjson%2Bfhir'
``` 
4. Point domains to the temp ELB by hand using the TF migration scripts
5. Test domain still work
```
curl --insecure --cert-type pem --cert client_data_server_local_test_env_dpr_keypair.pem  'https://bfd-prod-sbx.bfdcloud.net:443/v1/fhir/metadata?_format=application%2Fjson%2Bfhir'
``` 
6. Merge PR into master and deploy using Jenkins
7. Point domains to the new ELB
8. Disconnect from VPN
9. Test without a VPN connnection
```
curl --insecure --cert-type pem --cert client_data_server_local_test_env_dpr_keypair.pem  'https://bfd-prod-sbx.bfdcloud.net:443/v1/fhir/metadata?_format=application%2Fjson%2Bfhir'
``` 

**Testing**
A temp ELB was setup in prod-sbx using the PR's scripts. Connectivity was confirmed. 

**Security**
See SIA.

### CODE REVIEW

**Comment by RickHawesUSDS** [comment]
The TF plan for prod-sbx
```
  # module.stateless.module.fhir_lb.aws_elb.main must be replaced
-/+ resource "aws_elb" "main" {
      ~ arn                         = "arn:aws:elasticloadbalancing:us-east-1:577373831711:loadbalancer/bfd-prod-sbx-fhir" -> (known after apply)
      ~ availability_zones          = [
          - "us-east-1a",
          - "us-east-1b",
          - "us-east-1c",
        ] -> (known after apply)
        connection_draining         = true
        connection_draining_timeout = 60
        cross_zone_load_balancing   = false
      ~ dns_name                    = "internal-bfd-prod-sbx-fhir-1922876557.us-east-1.elb.amazonaws.com" -> (known after apply)
      ~ id                          = "bfd-prod-sbx-fhir" -> (known after apply)
        idle_timeout                = 60
      ~ instances                   = [
          - "i-035be7aa96b6aed02",
          - "i-0d09701ddb00d6aa5",
          - "i-0e22cb01af154bc66",
        ] -> (known after apply)
      ~ internal                    = true -> false # forces replacement
      ~ name                        = "bfd-prod-sbx-fhir" -> "bfd-prod-sbx-fhir-public" # forces replacement
        security_groups             = [
            "sg-05bb466a376bca3b3",
        ]
      ~ source_security_group       = "577373831711/bfd-prod-sbx-fhir-lb" -> (known after apply)
      ~ source_security_group_id    = "sg-05bb466a376bca3b3" -> (known after apply)
        subnets                     = [
            "subnet-02cc4a4e8d5ffdb11",
            "subnet-0c78ef1670dccb1da",
            "subnet-0fc4374e606087aac",
        ]
        tags                        = {
            "Environment" = "prod-sbx"
            "Layer"       = "dmz"
            "application" = "bfd"
            "business"    = "oeda"
            "role"        = "fhir"
            "stack"       = "prod-sbx"
        }
      ~ zone_id                     = "Z35SXDOTRQ7X7K" -> (known after apply)

        access_logs {
            bucket        = "bfd-prod-sbx-logs-577373831711"
            bucket_prefix = "fhir_elb_access_logs"
            enabled       = false
            interval      = 5
        }

        health_check {
            healthy_threshold   = 5
            interval            = 10
            target              = "TCP:7443"
            timeout             = 5
            unhealthy_threshold = 2
        }

      + listener {
          + instance_port     = 7443
          + instance_protocol = "TCP"
          + lb_port           = 443
          + lb_protocol       = "TCP"
        }
      - listener {
          - instance_port     = 7443 -> null
          - instance_protocol = "tcp" -> null
          - lb_port           = 443 -> null
          - lb_protocol       = "tcp" -> null
        }
    }

  # module.stateless.module.fhir_lb.aws_security_group.lb will be updated in-place
  ~ resource "aws_security_group" "lb" {
        arn                    = "arn:aws:ec2:us-east-1:577373831711:security-group/sg-05bb466a376bca3b3"
        description            = "Allow access to the fhir load-balancer"
        egress                 = [
            {
                cidr_blocks      = [
                    "10.252.16.0/21",
                ]
                description      = "To VPC instances"
                from_port        = 7443
                ipv6_cidr_blocks = []
                prefix_list_ids  = []
                protocol         = "tcp"
                security_groups  = []
                self             = false
                to_port          = 7443
            },
        ]
        id                     = "sg-05bb466a376bca3b3"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "Public Internet access"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          - {
              - cidr_blocks      = [
                  - "10.234.240.0/22",
                  - "10.234.252.0/22",
                  - "10.233.20.0/22",
                  - "10.133.148.0/22",
                  - "10.224.78.0/23",
                  - "10.246.44.0/23",
                  - "10.224.90.0/23",
                  - "10.244.24.0/21",
                  - "10.247.0.0/21",
                  - "10.252.32.0/22",
                  - "10.246.188.0/22",
                  - "10.224.108.0/22",
                  - "10.252.40.0/21",
                  - "10.252.16.0/21",
                ]
              - description      = "From VPC peerings, the MGMT VPC, and self"
              - from_port        = 443
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 443
            },
        ]
        name                   = "bfd-prod-sbx-fhir-lb"
        owner_id               = "577373831711"
        revoke_rules_on_delete = false
        tags                   = {
            "Environment" = "prod-sbx"
            "Layer"       = "dmz"
            "Name"        = "bfd-prod-sbx-fhir-lb"
            "application" = "bfd"
            "business"    = "oeda"
            "role"        = "fhir"
            "stack"       = "prod-sbx"
        }
        vpc_id                 = "vpc-0c891bb57e955f825"
    }

Plan: 1 to add, 1 to change, 1 to destroy.

------------------------------------------------------------------------
```

**Comment by RickHawesUSDS** [comment]
On bfd-test the TF plan is empty.
```
14:20:31 <bfd> ~/p/b/o/t/e/t/stateless> tf plan -var 'fhir_ami=ami-0a61352edf2166cb5' -var 'etl_ami=ami-0db10fbf710098bdc' -var 'ssh_key_name=bfd-test' -var 'git_branch_name=master' -var 'git_commit_id=1ada7c3590e9234bd8a292ffffc398e3fe22d5dd' -target=module.stateless.module.fhir_lb.aws_elb.main -target=module.stateless.module.fhir_lb.aws_security_group.lb
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.stateless.data.aws_vpc_peering_connection.peers[1]: Refreshing state...
module.stateless.data.aws_vpc_peering_connection.peers[0]: Refreshing state...
module.stateless.data.aws_route53_zone.local_zone: Refreshing state...
module.stateless.data.aws_vpc.mgmt: Refreshing state...
module.stateless.data.aws_caller_identity.current: Refreshing state...
module.stateless.data.aws_vpc.main: Refreshing state...
module.stateless.data.aws_s3_bucket.logs: Refreshing state...
module.stateless.module.fhir_lb.data.aws_subnet.app_subnets[0]: Refreshing state...
module.stateless.module.fhir_lb.data.aws_subnet.app_subnets[2]: Refreshing state...
module.stateless.module.fhir_lb.data.aws_subnet.app_subnets[1]: Refreshing state...
module.stateless.module.fhir_lb.aws_security_group.lb: Refreshing state... [id=sg-0d25576255b4d5dad]
module.stateless.module.fhir_lb.aws_elb.main: Refreshing state... [id=bfd-test-fhir]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by njdister** [comment]
@RickHawesUSDS I just want to confirm if "public only when ingress CIDRs contain 0.0.0.0/0" is a safe assumption for the LB module?  For example if we are ever required to whitelist CIDRs for security reasons.

**Comment by RickHawesUSDS** [comment]
> @RickHawesUSDS I just want to confirm if "public only when ingress CIDRs contain 0.0.0.0/0" is a safe assumption for the LB module? For example if we are ever required to whitelist CIDRs for security reasons.

Good point.

**Comment by RickHawesUSDS** [comment]
@njdister Look at the last change

**Pull request merged**
