### PR TITLE
BFD-151 timezone timestamp

### PR DESCRIPTION
**Pull request by keithdadkins**
**JIRA Ticket:**
[BFD-151](https://jira.cms.gov/browse/BFD-151)

**User Story or Bug Summary:**

As a BFD engineer, I need to be able to diagnose deployment timeouts or other things that might go wrong during an instance launch. Adding timestamps to operations during instance launch will greatly help in this process. Additionally, I need the ETL to be set to UTC in order to avoid miscommunication and other confusion around what time events are happening in our logs – especially given the distributed nature of our team. And to avoid common mistakes in analytics and data processing.

### What Does This PR Do?

1. Adds a timestamp to user_data script output to assist in debugging.
2. Sets the platinum build to use UTC timezone. Which, will in-turn, configure the local timezone to UTC for images/instances built on-top of platinum.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

- [ ] That manual testing has been performed on the user_data script.
- [ ] That we fully understand the implications of setting UTC at the platinum build level.
  - [ ] There may be gaps in logs once the new timezone in configured (if the logs were using the local EDT timezone and not UTC already)
  - [ ] If there are gaps, some alerts with time based thresholds may fire

We can easily configure the timezone independently for each server/service if needed, but unifying the timezone across all sites and services would be ideal.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment: N/A.
    * Does this PR add any new software dependencies? **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before?  **No** (not considering a timestamp "data" in this context, so no.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

Before merging, we need to build a new platinum image and deploy to test. Once deployed, verify:
- [x] All app logs in `/usr/local/bfd-server` have UTC timestamps
- [x] Primary system logs `/var/log/{messages,secure}` have UTC timestamps
- [x] The associated log groups in CloudWatch `/bfd/test/*` have UTC timestamps

### Submitter Checklist

Before requesting final review, I've gone through and verified that this PR complies with the following requirements:

* [x] I've refactored and rebased this PR (for help, see: [this](https://dev.to/maxwell_dev/the-git-rebase-introduction-i-wish-id-had) and [this](https://raphaelfabeni.com/git-editing-commits-part-1/), if needed, so that it is as small as it can reasonably be, in order to:
    1. Ensure that any problems it causes have a small "blast radius".
    2. Ensure that it'll be easier to rollback if that becomes necessary.
    3. Ease the burden on reviewers.
* [x] I've verified that the commits in this PR:
    1. Reasonably explain the "what" and "why" of the changes.
    2. Leverage JIRA's [smart commits](https://confluence.atlassian.com/jirasoftwarecloud/processing-issues-with-smart-commits-788960027.html) to reference the JIRA ticket that they're associated with. For example, aim for commit messages like this (note also [the 50/72 formatting](https://stackoverflow.com/q/2290016) used here):
        
        ```
        Added the whizbang to the doodad.

        The new whizbang should really simplify things for our whoosit users.
        It was a bit tricky to get it into the doodad, but we decided that the
        flipwhee pattern was the best approach for now. Might want to revisit
        that in the future if it ends up being too hard to maintain.

        SOMEPROJECT-42
        ```
        
* [x] I've verified that this PR includes all required documentation changes, including `README` updates and changelog / release notes entries.
* [x] I've verified that all new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] I've verified that all tech debt and/or shortcomings introduced by this PR is detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] I've requested review from at least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
* [x] I've requested review from any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [ link to engineering standards is broken ] I've verified that this PR and its changes comply with all other policies in the [DASG Engineering Standards](../policies/engineering_standards.md) and have specifically called out any/all deviations in this PR.

### CODE REVIEW

**Comment by njdister** [comment]
The things to check for once this is deployed in the test environment are:
- All app logs in `/usr/local/bfd-server` have UTC timestamps
- Primary system logs `/var/log/{messages,secure} have UTC timestamps
- The associated log groups in CloudWatch `/bfd/test/*` have UTC timestamps

**Comment by keithdadkins** [comment]
I need to test reverting the aws provider version and see if they fixed it upstream.

**Comment by njdister** [comment]
> I need to test reverting the aws provider version and see if they fixed it upstream.

Did you test this out?  If it's still broken it seems like unfortunately we will need to pin the AWS provider version in all environments for stateless.

**Comment by keithdadkins** [comment]
Rebased to include BFD-211: Fix for broken AWS terraform provider >= 2.61.0 (#286).

**Pull request merged**
