### PR TITLE
[BFD-635] R4 Carrier EOB Mapping

### PR DESCRIPTION
**Pull request by Dranith**
### Change Details

* Added V2 Carrier EOB Transformer
* Updated how HCPCS Code was mapped for Carrier and Inpatient (It now maps to `item.productOrService`) 
* Standardized how National Drug Code is mapped across Inpatient, Outpatient and Carrier (PDE maps differently so can't use this)

### Acceptance Validation

Sample A was mapped to R4 and run through the FHIR validator.  Any compliance issues have been documented.  Outstanding issues are almost entirely related to missing input data.

Additionally, roughly 300 IDs of each R4 EOB were randomly selected and pulled from the synthetic data to ensure no errors / failures.

### External References

- [BFD-635](https://jira.cms.gov/browse/BFD-635)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [x] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by mackec1 — APPROVED** [review]
Andrew. Code looks really nice; well organized, etc. I did not cross-check the code vs. the spec, but I have confidence that you did.

**Review by mackec1 — APPROVED** [review]
Andrew. I did foret one thing (and I have the same issue too!). We probably want to at least comment out the System.out where we dump the JSON so we can run it through the validator. The output shows up in the build which is not ideal.

**Comment by Dranith** [comment]
Yeah I thought about commenting that out, but I didn't mind the output in the build until more complete unit testing can be developed. I can update that though.

**Comment by jzulim** [comment]
Continued to be impressed with quality output and decyphering the r4 and carin specs. Bravo! :shipit:

**Review by jzulim — APPROVED** [review]
🚀

**Pull request merged**
