### PR TITLE
Cbrune/BFD-697 - errors related to Evidation/Heartline

### PR DESCRIPTION
**Pull request by cbrunefearless**
### Change Details
BFD-697 - errors related to Evidation/Heartline.. Checking for null in the beneficiary monthly table.  After looking into the incident, it looks like CCW is sending over nulls for partdcontract numbers.  This eliminates the bug that was found by BB2.

NOTE - When this ticket is pulled in, time-box the ticket and assign a date that the investigation should be completed by 

Background: 
BB2 has experienced a high number of errors stemming from Evidation on two occasions:   

Tuesday March 16 around 7:40PM EDT. 
Wednesday, March 17 around 11:45AM EDT
The team has also correlated these errors back to issues reported by Heartline in February.  Findings were:

Primarily all errors from 1 bene (FHIR ID can be provided in Keybase), but there are others within Evidation (total 77)
2 with coverage errors from BFD, 75 with EOB errors 
Nathan Dister has generated the following splunk query to help isolate these errors: 

Link to google doc with query - https://docs.google.com/document/d/1AD_TYbR49ahBbqrYcap5yUMNBGj35OUUOdA-8Q0wonU/edit?usp=sharing
note - for some reason Jira wouldn't let the query be in the ticket
User Story: 

As BB2, we want to understand what is causing these errors so we can help define an approach to resolving (either with BFD or with Evidation). 
Hypotheses are that there may be issues with the Data associated with these beneficiaries (ex: missing required fields) or Evidation could be performing unsupported FHIR operations
A/C: 

Splunk query parameters are reviewed and determination is made into which issues should be investigated (coverage, EOB, etc)

### Acceptance Validation
Check for validity of the fix, and when a null is set in a partD field

### Feedback Requested
Check that fixes the bug.

### External References

- [BFD-697](https://jira.cms.gov/browse/BFD-697)

### Security Implications

N/A
- [ ] new software dependencies

- [ ] altered security controls

N/A
- [ ] new data stored or transmitted

N/A
- [ ] security checklist is completed for this change

N/A
- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by jzulim — COMMENTED** [review]
Chris, could you please provide more context in the description for this PR? Also, can you help me understand how `partDContractId' can be `NULL` - I was under the impression we always got a 0 or a contract ID? If this field is optional in the rifloader this feels ok, but I'm curious if you can give more background and why this approach is needed in the PR description?

**Review by Dranith — APPROVED** [review]
Looks straight forward.

**Review by mackec1 — APPROVED** [review]
LGTM

**Review by rtravitz — COMMENTED** [review]
Should we have a test case enforcing this? Otherwise looks straightforward like others have said.

**Pull request merged**
