### PR TITLE
BLUEBUTTON-1359: Enable deploys to the CCS prod environment

### PR DESCRIPTION
**Pull request by karlmdavis**
Also cleaning up a couple of minor things in our `Jenkinsfile`, while I'm poking at it.

https://jira.cms.gov/browse/BLUEBUTTON-1359

### CODE REVIEW

**Comment by njdister** [comment]
Do you need to create the new lockable resource in Jenkins first or will it be created automatically?

**Comment by karlmdavis** [comment]
> Do you need to create the new lockable resource in Jenkins first or will it be created automatically?

@njdister Automagically. I _will_, however, have to go remove the old lock manually. Not that it's hurting anything, but still.

(FWIW, interesting to note that this kind of change would be a lot more dangerous if we weren't always building branches after merging in `master`.)

**Comment by karlmdavis** [comment]
Had to fix a syntax error, so pushed a commit for that, rebased, and sent out for review.

**Comment by karlmdavis** [comment]
Merging ahead of re-review, as this is low-risk and I'm pressed for time.

🤞

**Pull request merged**
