### PR TITLE
BFD-1663: Propose bfd-server startup check (RFC)

### PR DESCRIPTION
**Pull request by mjburling**
**JIRA Ticket:**
[BFD-1663](https://jira.cms.gov/browse/BFD-1663)

**User Story or Bug Summary:**

Propose bfd-server startup check.

---

### What Does This PR Do?

This RFC proposes a minor change to existing bfd-server on-host health checking to satisfy the requirements of a reliable startup check.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [x] Yes
      * [ ] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mariosmith90 — APPROVED** [review]

**Review by christrotteradhoc — DISMISSED** [review]
Great work here

**Review by StewGoin — COMMENTED** [review]
One question prior to approval -- is there a reason to go with an iptables DROP vs. a REJECT? I'm curious if a REJECT might be a better behavior since it gives a packet response vs. just ignoring.

**Comment by mjburling** [comment]
> One question prior to approval -- is there a reason to go with an iptables DROP vs. a REJECT? I'm curious if a REJECT might be a better behavior since it gives a packet response vs. just ignoring.

Given the simplicity of the solution, I honestly hadn't given it a second thought. I've read recently that VPC ACLs behave similarly to `DROP` rules, but the fact that we're proposing them here is a happy accident building off of the spike work @mariosmith90 and I did to inform the proposal. I don't believe the CLB's tcp ping's behavior will change based on meeting dropped vs rejected packets, but I am curious. The implementation *is available* to deploy from #1077 to the shared integration test environment (once things have calmed down there). I'll meditate on this before getting back to you. 

What's more, it might be nice from the debugging perspective if things go awry...

**Comment by StewGoin** [comment]
I'm good with whichever path forward makes sense, I just know from past experience that _not_ doing TCP according to spec can sometimes have unintended consequences and unless DROP provides an advantage to us it's probably worth doing a REJECT instead for troubleshooting, etc... like you said :)

**Comment by mjburling** [comment]
Thanks for the helpful feedback, @StewGoin. We all really appreciate it. tl;dr; there are advantages to playing by the rules and adopting `REJECT` over `DROP`. I'll adjust the proposal here and the implementation. Thanks!

<details><summary>More time to kill?</summary>

After giving this some more thought and running through a few different scenarios, I have to agree that `REJECT` is the intended behavior here–while it doesn't _really_ matter for **new** application instances, this will also bring better support for service restarts, which isn't really an *extreme* edge case when considering exceptional, out-of-band fixes that may have an operator making manual adjustments and restarting the service. This isn't really supported today, but there is appetite for developing automated workflows that will make these exceptional changes easier, more predictable, and safer.

> not doing TCP according to spec can sometimes have unintended consequences

So, it _does_ matter for new instances, too. The health check is needlessly waiting on 5-second timeouts when we could otherwise clearly communicate that the service does exist, it just hasn't fully started and won't accept traffic. That's in keeping with the spirit of the startup check. Let's send the right signal.

</details>

**Review by christrotteradhoc — DISMISSED** [review]

**Comment by keithdadkins** [comment]
I would not have the bfd service account manage firewall rules, have a separate service do that instead. This can easily be accomplished with a few systemd units:
- One to enable/restore iptables on boot (base rules, established traffic, loopbacks, ssh, etc)
- And a second to run your health-check script forwarding/rejecting 7443 as desired

These units can run privileged, so no need to elevate bfd's service account privs. And systemd allows us to take advantage of service dependencies, survive reboots, etc. Ie., healthchecker depends on bfd, iptables depends on network. KISS

**Comment by mjburling** [comment]
> [...]
> This can easily be accomplished with a few systemd units:
> 
> * One to enable/restore iptables on boot (base rules, established traffic, loopbacks, ssh, etc)
> * And a second to run your health-check script forwarding/rejecting 7443 as desired
> [...] KISS

I considered this very implementation! Ultimately, I opted for something simpler. But, maybe simplicity is in the eye of the beholder? I've reduced and added these comments to the future possibilities section. Thanks!

> And systemd allows us to take advantage of service dependencies, survive reboots, etc.

Explicit dependencies *are* great, but I don't think we can make the dependency relationships any clearer than how they are already defined within the same function today. Surviving reboots might be nice too, but this proposal doesn't include any provisions for reboot survivability; when outside the initial 430s ASG grace period, bfd-server application instances are terminated after 2-consecutive unhealthy checks over 20 seconds as reported by the CLB. A rebooted instance would certainly be out of service long enough to trigger replaceent, systemd units or otherwise.

**Review by keithdadkins — APPROVED** [review]

**Review by christrotteradhoc — APPROVED** [review]

**Pull request merged**
