### PR TITLE
BFD-2633: Ensure Timezone Consistency Across Server

### PR DESCRIPTION
**Pull request by JeremyIR**
**JIRA Ticket:**
[BFD-2633](https://jira.cms.gov/browse/BFD-2633)

**User Story or Bug Summary:**

As a BFD user I want the timezones in the response to be consistent so that I do not have to do any additional work parsing timezones in my business logic.

---

### What Does This PR Do?

2+ years ago an engineer using our code to validate EOB data claimed they were failing a unit test related to an inpatient procedure, and claimed it was because there was a timezone offset. Upon further inspection, this is not the case, as for the few tests where we have mock data with a timezone thats not UTC i.e. "2016-01-16T00:00:00-06:00", when we create a procedure we use a method called convertToDate which takes a localDate format strips everything except the month and day of that date, and then creates a Date from an Instant in UTC. So if we pass in "2016-01-16T00:00:00-06:00" we will end up getting back "2016-01-16T00:00:00+00:00" at the end of the day. Additionally the engineer that implemented the converToDate method had timezone shift avoidance in consideration when writing it. Hence why our unit tests never have failed when we were creating procedures and passing in values like "2016-01-16T00:00:00-06:00" as the date. SO to avoid future confusion, I have:

Updated the unit and integration tests to include timezones in UTC when a timestamp is involved.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mjburling — COMMENTED** [review]
`+00:00` makes sense to me, but I am curious about the scope. 

Can you try running the following from the root on your branch and see what you come up with?

`grep -I --extended-regexp '(\+|-)0[^0]:00' --recursive  apps/`

**Comment by JeremyIR** [comment]
> `+00:00` makes sense to me, but I am curious about the scope.
> 
> Can you try running the following from the root on your branch and see what you come up with?
> 
> `grep -I --extended-regexp '(\+|-)0[^0]:00' --recursive apps/`

Thanks. Forgot to commit updating the ITs

**Review by lsmitchell — APPROVED** [review]

**Comment by lsmitchell** [comment]
Approved pending build passes.

**Comment by JeremyIR** [comment]
> Approved pending build passes. (Or whatever part of this is failing the CI checks)

Build passing now

**Review by lsmitchell — APPROVED** [review]

**Review by mackec1 — APPROVED** [review]

**Pull request merged**
