### PR TITLE
BFD-465: Updating Java dependencies to resolve security vulnerabilities 

### PR DESCRIPTION
**Pull request by jzulim**
### Change Details

Bumped up the following java deps to resolve security vulnerabilities:

jackson-databind
guava
spring-framework-bom
spark-sketch_2.12

### Acceptance Validation

Do CI Checks Pass?
Do these updates resolve the vulnerabilities? 

### Before Merging
I intend to deploy this to test and run a bunch of smoke tests to check for edge cases our unit or iT tests MIGHT not catch. 

### Feedback Requested

Should we update any other packages?

### External References

- [BFD-465](https://jira.cms.gov/browse/BFD-465)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by cbrunefearless — DISMISSED** [review]
LGTM

**Review by dshekhar18 — APPROVED** [review]
Looks Good! Thanks for updating the Java dependencies.

**Review by keithdadkins — APPROVED** [review]
Looks good.

**Review by cbrunefearless — APPROVED** [review]
LGTM

**Pull request merged**
