### PR TITLE
[BFD-1025] Fix BFD Perf Test failing IT's

### PR DESCRIPTION
**Pull request by jzulim**
### Change Details

Removes the slf4j-nop exclusion from the defunct BFD Perf Test application so IT's may pass. 

### Acceptance Validation

Do all IT's pass?

### Feedback Requested

Who wants to reach out to @karlmdavis and see if we should nuke this code? 

### External References

- [BFD-1025](https://jira.cms.gov/browse/BFD-1025)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by brianburton — APPROVED** [review]
Looks good to me.

**Review by JeremyIR — APPROVED** [review]
Nice!

**Review by cbrunefearless — APPROVED** [review]
lgtm

**Review by mackec1 — APPROVED** [review]

**Comment by karlmdavis** [comment]
@jzulim Is this actually causing problems? I haven't had any build failures related to this myself, though I've had some console warnings when launching the server.

**Pull request closed without merging**
