### PR TITLE
BFD-3111: Fix build errors caused by file permissions

### PR DESCRIPTION
**Pull request by brianburton**
**JIRA Ticket:**
[BFD-3111](https://jira.cms.gov/browse/BFD-3111)

**User Story or Bug Summary:**

As a BFD engineer I want to be able to build the application multiple times without using clean.

---

### What Does This PR Do?

Changes the `bfd-server-launcher` assembly to use make `bfd-server-launcher.sh` writable.  This avoids the permissions error when maven expands the zip file over already existing files.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by brandoncruz3 — APPROVED** [review]

**Review by mackec1 — APPROVED** [review]

**Review by mjburling — CHANGES_REQUESTED** [review]
Just double checking here... is this really necessary? I was glancing at the assembly configuration under the `zip.xml`, and noticed what I would argue is an inappropriate `fileMode`. Changing that from `0500` (write restriction from the owner? really?) to the default `0644` seemed to fix the issue for me... is this just misconfiguration/misuse?

**Comment by brianburton** [comment]
> Just double checking here... is this really necessary? I was glancing at the assembly configuration under the `zip.xml`, and noticed what I would argue is an inappropriate `fileMode`. Changing that from `0500` (write restriction from the owner? really?) to the default `0644` seemed to fix the issue for me... is this just misconfiguration/misuse?

As long as we are certain that the more restrictive file mode is not part of our security strategy that would be fine by me.

**Comment by mjburling** [comment]
> > Just double checking here... is this really necessary? I was glancing at the assembly configuration under the `zip.xml`, and noticed what I would argue is an inappropriate `fileMode`. Changing that from `0500` (write restriction from the owner? really?) to the default `0644` seemed to fix the issue for me... is this just misconfiguration/misuse?
> 
> As long as we are certain that the more restrictive file mode is not part of our security strategy that would be fine by me.

That's a good thought–in the end, ansible is responsible for the last configuration details. While it _does_ inherit the 0500 mode from the assembled zip archive, I don't think I would say that we're particularly dependent on one dependency's file mode for secure functionality in bfd-server, i.e. the systemd service's ExecStart script's launcher/helper script. Ansible is already encoding `0775` on the calling ExecStart script ¯\_(ツ)_/¯. If there really are concerns over e.g. `0500` vs `0700` (it **does** need to be executable) or otherwise, this would be more appropriately defined explicitly in the `bfd-server` ansible role–I could be convinced otherwise, but I don't think that is necessary.

If you can update the single line in the `zip.xml` assembly configuration and your evaluations support that this is a successful change, I think that would be a more auspicious change.

**Review by aadedejifearless — APPROVED** [review]
LGTM

**Comment by brianburton** [comment]
I agree about the alternate solution.  None of the other files in the zip have restricted permissions.  So a nefarious actor could simply replace a jar file under this configuration.  Per @mjburling 's recommendation I'll simplify this to just make the script writable within the zip file.

**Review by aadedejifearless — APPROVED** [review]

**Review by mackec1 — APPROVED** [review]

**Review by mjburling — APPROVED** [review]

**Pull request merged**
