### PR TITLE
BFD-2767: Upgrade Out of Date Dependencies

### PR DESCRIPTION
**Pull request by JeremyIR**
**JIRA Ticket:**
[BFD-2767](https://jira.cms.gov/browse/BFD-2767)

**User Story or Bug Summary:**

This PR addresses several library/dependency updates. 

SNYK and Performance Test Results:
- Performance regression tests were conducted on both this branch with upgraded dependency versions, and the master branch on TEST server. The number of requests differed by 5.53%, and the average number of requests/second differed by 5.64%.

<details>
<summary>
TEST Server Master Branch

</summary>

```
Type     Name                                                                          # reqs      # fails \|    Avg     Min     Max    Med \|   req/s  failures/s
--
--------\|----------------------------------------------------------------------------\|-------\|-------------\|-------\|-------\|-------\|-------\|--------\|-----------
GET      /v2/fhir/Coverage search by id                                                   301     0(0.00%) \|     37       9     775     13 \|    9.52        0.00
GET      /v2/fhir/Coverage search by id / count=10                                        268     0(0.00%) \|     38       8     576     15 \|    8.47        0.00
GET      /v2/fhir/ExplanationOfBenefit search by id                                       270     0(0.00%) \|    275      64    1662    210 \|    8.54        0.00
GET      /v2/fhir/ExplanationOfBenefit search by id / count=10                            272     0(0.00%) \|    199      69     836    150 \|    8.60        0.00
GET      /v2/fhir/ExplanationOfBenefit search by id / includeTaxNumbers                   293     0(0.00%) \|    251      77    1411    190 \|    9.26        0.00
GET      /v2/fhir/Patient search by coverage contract (all pages)                         282     0(0.00%) \|     46      13     743     22 \|    8.91        0.00
GET      /v2/fhir/Patient search by hashed mbi / includeIdentifiers = mbi                 300     0(0.00%) \|     46       3     832      9 \|    9.48        0.00
GET      /v2/fhir/Patient search by id                                                    278     0(0.00%) \|     33       4     832      9 \|    8.79        0.00
GET      /v2/fhir/Patient search by id / _IncludeIdentifiers=mbi                          299     0(0.00%) \|     38       4     832      9 \|    9.45        0.00
--------\|----------------------------------------------------------------------------\|-------\|-------------\|-------\|-------\|-------\|-------\|--------\|-----------
Aggregated                                                                      2563     0(0.00%) \|    106       3    1662     24 \|   81.02        0.00
Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------\|--------------------------------------------------------------------------------\|--------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------
GET      /v2/fhir/Coverage search by id                                                         13     15     21     33     84    120    290    510    780    780    780    301
GET      /v2/fhir/Coverage search by id / count=10                                              15     19     31     50    110    140    200    340    580    580    580    268
GET      /v2/fhir/ExplanationOfBenefit search by id                                            210    260    290    340    530    770   1100   1300   1700   1700   1700    270
GET      /v2/fhir/ExplanationOfBenefit search by id / count=10                                 150    180    220    240    410    570    640    650    840    840    840    272
GET      /v2/fhir/ExplanationOfBenefit search by id / includeTaxNumbers                        190    230    260    290    430    680   1100   1200   1400   1400   1400    293
GET      /v2/fhir/Patient search by coverage contract (all pages)                               22     25     33     47     98    140    340    440    740    740    740    282
GET      /v2/fhir/Patient search by hashed mbi / includeIdentifiers = mbi                        9     12     19     29     98    140    740    780    830    830    830    300
GET      /v2/fhir/Patient search by id                                                           9     10     13     18     86    120    390    550    830    830    830    278
GET      /v2/fhir/Patient search by id / _IncludeIdentifiers=mbi                                 9     12     21     38    110    150    390    590    830    830    830    299
--------\|--------------------------------------------------------------------------------\|--------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------
Aggregated                                                                             24    110    140    170    260    410    640    810   1400   1700   1700   2563
```

</details>

<details>
<summary>
TEST Server UPGRADES:

</summary>

```
Type     Name                                                                          # reqs      # fails \|    Avg     Min     Max    Med \|   req/s  failures/s
--
--------\|----------------------------------------------------------------------------\|-------\|-------------\|-------\|-------\|-------\|-------\|--------\|-----------
GET      /v2/fhir/Coverage search by id                                                   277     0(0.00%) \|     43       9     525     14 \|    8.75        0.00
GET      /v2/fhir/Coverage search by id / count=10                                        277     0(0.00%) \|     47       9     909     14 \|    8.75        0.00
GET      /v2/fhir/ExplanationOfBenefit search by id                                       271     0(0.00%) \|    262      75    1358    200 \|    8.56        0.00
GET      /v2/fhir/ExplanationOfBenefit search by id / count=10                            240     0(0.00%) \|    209      60     704    160 \|    7.58        0.00
GET      /v2/fhir/ExplanationOfBenefit search by id / includeTaxNumbers                   262     0(0.00%) \|    269      70    1357    210 \|    8.27        0.00
GET      /v2/fhir/Patient search by coverage contract (all pages)                         265     0(0.00%) \|     57      13     578     22 \|    8.37        0.00
GET      /v2/fhir/Patient search by hashed mbi / includeIdentifiers = mbi                 276     0(0.00%) \|     38       4     910      9 \|    8.71        0.00
GET      /v2/fhir/Patient search by id                                                    277     0(0.00%) \|     44       6     909      9 \|    8.75        0.00
GET      /v2/fhir/Patient search by id / _IncludeIdentifiers=mbi                          280     0(0.00%) \|     33       5     601      9 \|    8.84        0.00
--------\|----------------------------------------------------------------------------\|-------\|-------------\|-------\|-------\|-------\|-------\|--------\|-----------
Aggregated                                                                      2425     0(0.00%) \|    109       4    1358     24 \|   76.57        0.00
Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------\|--------------------------------------------------------------------------------\|--------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------
GET      /v2/fhir/Coverage search by id                                                         14     18     31     46    130    160    300    400    520    520    520    277
GET      /v2/fhir/Coverage search by id / count=10                                              14     17     27     42    130    180    400    580    910    910    910    277
GET      /v2/fhir/ExplanationOfBenefit search by id                                            200    250    290    320    470    620    910   1300   1400   1400   1400    271
GET      /v2/fhir/ExplanationOfBenefit search by id / count=10                                 160    210    240    270    400    560    650    700    700    700    700    240
GET      /v2/fhir/ExplanationOfBenefit search by id / includeTaxNumbers                        210    270    300    340    450    720    940   1200   1400   1400   1400    262
GET      /v2/fhir/Patient search by coverage contract (all pages)                               22     27     38     66    140    250    380    480    580    580    580    265
GET      /v2/fhir/Patient search by hashed mbi / includeIdentifiers = mbi                        9     11     15     24    120    180    380    530    910    910    910    276
GET      /v2/fhir/Patient search by id                                                           9     10     14     26    100    220    410    760    910    910    910    277
GET      /v2/fhir/Patient search by id / _IncludeIdentifiers=mbi                                 9     11     17     28    120    150    270    400    600    600    600    280
--------\|--------------------------------------------------------------------------------\|--------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------\|------
Aggregated                                                                             24    120    160    180    280    390    620    760   1400   1400   1400   2425
```
</details>

### What Does This PR Do?

Change library versions to more secure. Update invocations of the DefaultS3TransferManager due to its deprecation.

### What Should Reviewers Watch For?

Does the code follow style guidelines?
Have all the libraries in question been addressed and contribute to lower vulnerability when running snyk?
If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by mackec1 — COMMENTED** [review]
Just a question on the S3 change(s); so your test results are applicable for BFD services which tested things like HAPI FHIR version upgrade, etc.

Did you do any S3 tests? The reason I ask is there is some chatter on S3 memory leaks, depending on how the S3 interface is used (close vs. previous shutdownNow).

**Comment by JeremyIR** [comment]
> Just a question on the S3 change(s); so your test results are applicable for BFD services which tested things like HAPI FHIR version upgrade, etc.
> 
> Did you do any S3 tests? The reason I ask is there is some chatter on S3 memory leaks, depending on how the S3 interface is used (close vs. previous shutdownNow).

No but that makes sense. Going to just forgo upgrading AWS java SDK right now. Especially since Brian is doing some S3 DAO work. Will create a separate ticket

**Review by lsmitchell — APPROVED** [review]
Seems like all minor updates now, so _should_ be safe.

**Review by mackec1 — APPROVED** [review]
Looks good; I was going to bring up Brian's work on S3 so good to see that it's removed from this effort. Thx.

**Pull request merged**
