### PR TITLE
AB2D-2195 OR condition

### PR DESCRIPTION
**Pull request by adaykin**
### Acceptance Validation

Whether all code paths are working properly if an identifier is passed or not.

### Feedback Requested

Will results be the same as they previously were with the same API call? The results from previously used API calls should not change at all with this PR.

### External References

- [BLUEBUTTON-xxx](https://jira.cms.gov/browse/BLUEBUTTON-xxx)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### CODE REVIEW

**Review by cbrunefearless — APPROVED** [review]
LGTM

**Review by dshekhar18 — COMMENTED** [review]
@adaykin Andy, were you able to deploy this in BFD-TEST and run it against some Bene data?

**Comment by jzulim** [comment]
No progress has been made on this for some time. I also can't find a feature / story that correlates with this change - I've reached out to the AB2D engineering team to see if they intend to proceed with this. @nflearl @lailasharshar @wnyffenegger

**Comment by nflearl** [comment]
This PR is OBE - overtaken by events.  With the changes to the API requesting on a year basis, we have pivoted away from the concept of multi-month requests.

**Comment by jzulim** [comment]
Thanks for the update AB2D. Closing this one out.

**Pull request closed without merging**
